add Bitmark
bisq-network/bisq pull request #1669
Opened 2018-09-09 22:14 UTC by bitmark-protocol

If you need extra parts to the commit (like test cases), let me know. I just copied and pasted what I saw for Namecoin, which is a similar coin (both based on Bitcoin).

The version of Bitmark I want to use may different than what will soon be listed on other exchanges. The "official team" wants to add a controversial fork that is obviously a scam and departs from the honest protocol that Bitmark maintained throughout the years. You can se the discussion here: https://bitcointalk.org/index.php?topic=3169983.msg43299842#msg43299842

If you want call it "Bitmark Classic", but the ticker name BTM shouldn't conflict because the team of investors controlling the alternate repo (project-bitmark) want the ticker name to be MARKS.

The repo I want to be used is the one created by this account (bitmark-protocol/bitmark). The explorer: https://explorer.bitmark.cc

2018-09-10 17:52 UTC, bitmark-protocol commented
Their fork failed to launch, so it is uncertain what direction the "team" will take, but at least lets get the current version of Bitmark on this and then we can split it in 2 if there are 2 forks. Thanks

2018-10-05 15:29 UTC, blabno requested changes
NACK. No PRs from master.

2018-10-05 18:07 UTC, bitmark-protocol commented
Hello @blabno. I don't understand? What Pull requests from master are you talking about?

2018-10-05 18:18 UTC, bitmark-protocol commented
Ah you mean to use a branch "list-bitmark" to do the pull request?

2018-10-15 13:57 UTC, blabno commented
@bitmark-protocol yes, create `list-bitmark` branch and create pull request from there.

2018-10-31 23:29 UTC, ManfredKarrer commented
Closed as not updated after 2 weeks. Open again after it is fixed.

2018-10-31 23:29 UTC, closed without merging