List SpaceCash (SPACE)
bisq-network/bisq pull request #1766
Opened 2018-10-10 07:33 UTC by tlightsky

Official project URL: http://hspace.app
Official block explorer URL: https://hyperstats.info/

This is a resubmission of https://github.com/bisq-network/bisq-assets/pull/94 (ACKed by @blabno)

2018-10-11 03:17 UTC, MasterHW commented
note: URL is https://hspace.app/

2018-10-11 03:20 UTC, tlightsky commented
@MasterHW thanks, changed that

2018-10-12 03:36 UTC, OTC-Buyer commented
Shouldn't it be .... Hyperspace (SPACE) .... just want to make sure, thought name of project should be name ... yes I realize we call it SpaceCash but coin name needs to reflect project name ... SPACE is just short for SpaceCash which is only how you say the coin

2018-10-15 14:26 UTC, blabno requested changes
NACK Add newlines at the end of files

2018-10-15 14:26 UTC, blabno commented
@OTC-Buyer could you be more clear?

2018-10-15 17:14 UTC, OTC-Buyer commented
I just read on Discord that Mark is using symbol ticket of “HS” now so it may not matter.

2018-10-16 04:19 UTC, tlightsky commented
@blabno added newlines at the end of files

2018-10-17 04:35 UTC, tlightsky commented
change ticker from SPACE to XSC

2018-11-15 08:21 UTC, blabno commented
@cryptoluka Please rebase against master and resolve conflicts.

2018-11-26 01:37 UTC, ManfredKarrer commented
Close as no response from dev. Also we have a code freeze for new release soon.

2018-11-26 01:37 UTC, closed without merging