List Greencoin (GRN)
bisq-network/bisq pull request #1773
Opened 2018-10-13 17:27 UTC by CryptorClub

Site: http://greencoin.life
Web wallet: https://wallet.greencoin.life
Official pool: https://greencoin.space
Explorer: http://explorer.greencoin.space
Source code: https://github.com/CryptorClub/GreenCoin

ANN: https://bitcointalk.org/index.php?topic=3103301

2018-11-15 08:26 UTC, blabno commented
Please do not use Travis as your local test runner.
Squash those commits with proper message.

2018-11-15 08:27 UTC, blabno requested changes
NACK per comments

2018-11-15 08:27 UTC, blabno commented on assets/src/main/java/bisq/asset/coins/Greencoin.java
> +        super("Greencoin", "GRN", new DefaultAddressValidator());
Do not use deprecated `DefaultAddressValidator`

2018-11-15 09:19 UTC, CryptorClub commented
@blabno please give me example links of pull requests of coins, that have correct code

2018-11-16 11:17 UTC, CryptorClub commented on assets/src/main/java/bisq/asset/coins/Greencoin.java
> +        super("Greencoin", "GRN", new DefaultAddressValidator());
I've use Base58 validator

2018-11-16 11:19 UTC, CryptorClub commented
> Please do not use Travis as your local test runner.
> Squash those commits with proper message.

How to use another test runner? It seems, that it was runned automatically, when I published commit...
I've squashed commits into one.

2018-12-19 07:30 UTC, blabno commented
Apply Bisq code style and resolve conflicts.

2018-12-19 08:07 UTC, blabno commented
Is this ICO https://icobench.com/ico/greencoin ?

2018-12-19 16:36 UTC, ManfredKarrer commented
Greencoin is an ICO coin. Bisq does not list ICO coins.

2018-12-19 16:36 UTC, closed without merging

2018-12-20 12:51 UTC, CryptorClub commented
1. GreenCoin GRN is not GNC coin. And isn't ICO