Update to JDK11
bisq-network/bisq pull request #1810
Opened 2018-10-24 06:31 UTC by devinbileck

For fun, I decided to try JDK11 again and whaddya know, it actually worked this time :)

We can now build using either Oracle JDK or OpenJDK.

Resolves https://github.com/bisq-network/bisq/issues/1787

2018-10-24 06:39 UTC, devinbileck commented
However, I have no idea if anything needs to be updated as a result of switching to Java 11. I heard that when switching to Java 10, default libraries were used for crypto libs. So someone may need to review that (beyond my expertise).

2018-10-24 08:04 UTC, ripcurlx commented
@devinbileck So you didn't run into any issues anymore when your ran `gradle build`?

2018-10-24 16:27 UTC, devinbileck commented
@ripcurlx `gradlew build` was successful :)
I was also able to run the desktop application successfully. Although I didn't do any extensive testing.

Looking at the gradle output in more detail, there are some deprecation warnings with some java files, but I believe they also exist in master. But should still be investigated.

We will also need to look into this before moving to Gradle 5:
```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
```

2018-10-24 18:46 UTC, ManfredKarrer commented
Maybe @cbeams could add his input regarding Gradle 5 support

2018-10-24 19:02 UTC, ripcurlx commented
@devinbileck Sounds great! I'll give it a try with a release build tomorrow.

2018-10-25 08:01 UTC, ripcurlx commented
@devinbileck I ran `./gradlew build` (macOS 10.13.6, Oracle JDK 11.0.1) but got following error:
```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/christoph/Documents/Workspaces/Java/mono-repo/bisq/core/build.gradle' line: 71

* What went wrong:
A problem occurred evaluating project ':core'.
> Could not resolve all files for configuration ':core:testCompile'.
   > Could not resolve com.github.MicroUtils:kotlin-logging:3aedaa9310.
     Required by:
         project :core > project :p2p > com.github.JesusMcCloud.netlayer:tor.native:0.4.2
         project :core > project :p2p > com.github.JesusMcCloud.netlayer:tor.native:0.4.2 > com.github.JesusMcCloud.netlayer:tor:0.4.2
      > Could not resolve com.github.MicroUtils:kotlin-logging:3aedaa9310.
         > Could not get resource 'https://jitpack.io/com/github/MicroUtils/kotlin-logging/3aedaa9310/kotlin-logging-3aedaa9310.pom'.
            > Could not HEAD 'https://jitpack.io/com/github/MicroUtils/kotlin-logging/3aedaa9310/kotlin-logging-3aedaa9310.pom'.
               > peer not authenticated
```

@ManfredKarrer Does it run on your local setup?

2018-10-25 08:14 UTC, mrosseel commented
untested, but this seems not really a JDK error but a dependency which is not found. Maybe @devinbileck has this jar in his cache and you don't?

2018-10-25 08:17 UTC, ripcurlx commented
Changing in the p2p/build.gradle file the jcenter url worked for me (https://stackoverflow.com/questions/22887829/peer-not-authenticated-while-importing-gradle-project-in-eclipse):
**Before**
```
repositories {
    jcenter()
    maven { url 'https://jitpack.io' }
    maven { url 'https://raw.githubusercontent.com/JesusMcCloud/tor-binary/master/release/' }
}
```
**After**
```
repositories {
    jcenter {
        url "http://jcenter.bintray.com/"
    }
    maven { url 'https://jitpack.io' }
    maven { url 'https://raw.githubusercontent.com/JesusMcCloud/tor-binary/master/release/' }
}
```

2018-10-25 08:33 UTC, ripcurlx commented
Just tried to run a release build and recognized that javapackager is gone from the JDK 11 as well 🤦‍♂️. So we need to find an alternative and/or wait until the openjdk guys have it re-implemented (https://openjdk.java.net/jeps/343).

2018-10-25 15:33 UTC, devinbileck commented
> Changing the jcenter url in the p2p/build.gradle file worked for me

That's interesting. I don't know what the default URL is, or why you wouldn't be able to resolve it. I wonder if that is a permanent change we need to make to all the build.gradle files.

> Just tried to run a release build and recognized that javapackager is gone from the JDK 11

D'oh!

2018-10-26 00:45 UTC, ManfredKarrer commented
Does Oracle has some real plan with those aggressive relaese policies? I fear not. People will learn and ignore the next updates...

2018-10-29 16:51 UTC, cbeams commented
> Does Oracle has some real plan with those aggressive release policies? I fear not. People will learn and ignore the next updates...

This presentation from CodeOne (formerly JavaOne) was just published a few days ago:

 - The Future of Java SE: https://www.youtube.com/watch?v=MFfTqUQxFTs

I haven't watched it fully, but it seems to address exactly this topic. If anyone does watch it and can provide a summary, it would be appreciated.

2018-10-31 06:06 UTC, devinbileck commented
@cbeams That is a very informative video. Oracle is switching to a much more agile process with a major version released every 6 months, allowing them to include new functionality much sooner than their previous release process (every few years) and be able to decide what to include in a release just a few months prior. Each release will essentially be superseded by the next, but an LTS version will be released every 3 years and be supported for 8 years. So most people I assume will just stick to the LTS versions, but if you want a new feature in between, you can try it out but I guess will be forced to upgrade every 6 months until the next LTS if you really need it.

![image](https://user-images.githubusercontent.com/603793/47769199-38bf4900-dc98-11e8-9faf-9f884dafc0aa.png)

2018-11-01 17:06 UTC, ManfredKarrer commented
I will add a WIP prefix as it seems that the PR is not ready to get merges as long we don't have a solution for the javapackager.

2018-11-02 14:53 UTC, cbeams requested changes
NACK, for minor reasons detailed in the review comments, but mostly for lack of `javapackager` support in JDK 11, as has been mentioned by others above. I did some research here, and there's good news—an implementation of the new `jpackager` tool specified in [JEP 343](https://openjdk.java.net/jeps/343) is under review now.

Here's the announcement on the OpenJDK core-libs-dev mailing list: http://mail.openjdk.java.net/pipermail/core-libs-dev/2018-October/056186.html. A review thread ensues, but it's pretty low-level, probably not worth reading in detail for the stuff we care about.

There's a higher-level discussion about the new implementation in r/Java at https://www.reddit.com/r/java/comments/9qz61j/new_java_packager_tool_under_review_jep_343/.

I haven't done an option-by-option gap analysis to see if the new implementation will have everything we need, but from what I've gathered so far, it will. I think we're using `javapackager` in a pretty simple way right now, and while the new `jpackager` "drops support for JavaFX-specific features", I don't think we were using any of those anyway. See https://openjdk.java.net/jeps/343#Non-Goals for a complete list of what's getting dropped from the new implementation.

Excerpted from the results of `git grep -A20 javapackager` run at the root of the repo, here's our invocation of `javapackager` for macOS:

```
$JAVA_HOME/bin/javapackager \
    -deploy \
    -BappVersion=$version \
    -Bmac.CFBundleIdentifier=io.bisq.CAT \
    -Bmac.CFBundleName=Bisq \
    -Bicon=package/macosx/Bisq.icns \
    -Bruntime="$JAVA_HOME/jre" \
    -native dmg \
    -name Bisq \
    -title Bisq \
    -vendor Bisq \
    -outdir deploy \
    -srcdir deploy \
    -srcfiles "Bisq-$version.jar" \
    -appclass bisq.desktop.app.BisqAppMain \
    -outfile Bisq
```

I don't see any "JavaFX-specific" stuff there, though it might be worth going through each option (in particular the various `-B` flags) to ensure they have some equivalent in the new implementation.

As far as staying up-to-date on when `jpackager` will become available, there is a JIRA issue at https://bugs.openjdk.java.net/browse/JDK-8200758 that one could theoretically subscribe to in order to get updates, but there seems to be no way to create an account for that JIRA instance. I've emailed the OpenJDK team to ask about that, and will subscribe if I get an answer.

In any case, we need to wait on upgrading to JDK 11 for this, so I'd say we just leave this as a WIP for the time being. @devinbileck (or anyone else feeling up to it), you could make sure the new implementation has everything we need in the meantime, and weigh in on the core-dev-libs mailing list if it doesn't. They'd probably appreciate the real-world review.

2018-11-02 14:53 UTC, cbeams commented on .travis.yml
> +    - openjdk11
I wouldn't build with both. It'll make the CI builds take 2x as long, and it's probably better in the end to keep things simple and tell everybody they just need to install OpenJDK and forget about the Oracle JDK going forward.

2018-11-02 14:53 UTC, cbeams commented on README.md
> +You will need either [Oracle JDK 11](https://www.oracle.com/technetwork/java/javase/downloads/jdk11-downloads-5066655.html) or [OpenJDK JDK 11](https://jdk.java.net/11/) installed to complete the fol
Same as above; let's just keep it to OpenJDK 11. Note that there's a typo (not introduced by this PR) here: `Open JDK JDK 11` should just be `OpenJDK 11`.

2018-11-02 14:53 UTC, cbeams commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-bin.zip
This should (now) be `5.0-rc-1`, which is apparently the first release to officially support JDK 11 (even though everything builds just fine for me under `4.9`).

See https://docs.gradle.org/5.0-rc-1/release-notes.html#java-11-runtime-support

2018-11-02 14:59 UTC, cbeams commented
@devinbileck wrote

> That is a very informative video. Oracle is switching to a much more agile process with a major version released every 6 months, allowing them to include new functionality much sooner than their previous release process [...]

Thanks for the summary. I ended up watching about half of it as well, and agree it was well-worth it. These are big changes, and from what I gather they seem reasonable. I'm glad in any case that we won't any longer find ourselves in the seemingly interminable wait-state of so many previous JDK releases.

In my research above, I found another couple resources related to this topic that are worth sharing. I didn't read either in full, just scanned them, but the first looks to answer a lot of questions about the new licensing and release process, and the second provides a lot of detail on changes in JDK 11.

 - https://medium.com/@javachampions/java-is-still-free-c02aef8c9e04
 - https://news.kynosarges.org/2018/09/26/java-se-11-the-great-removal/

2019-01-06 03:29 UTC, ManfredKarrer commented
After that painful experience with updating to Java 9 and 10 I would avoid to lose again several months of deverloper time on infrastructural efforts (we still have issues with BitcoinJ now to get it updated to Java 10). So even if we manage to get Java 11 running and a packager is available I would like to wait 6-12 months until the ecosystem has gained sufficient maturity that we don't act again as alpha testers. 
As I don't see a near term horizon to get there I would prefer to close that PR as it would stay dangling for much longer. 
@devinbileck Is it ok for you to close that, or do you prefer to keep it open?

2019-01-06 08:13 UTC, devinbileck commented
@ManfredKarrer Agreed. I will close this.

2019-01-06 08:13 UTC, closed without merging