List Mask (MASK)
bisq-network/bisq pull request #1838
Opened 2018-10-29 12:30 UTC by diablax

- Official project URL: https://mask.team
- Official block explorer URL: http://explorer.mask.team

2018-11-05 07:09 UTC, cbeams requested changes
NACK. Squash to a single commit per instructions at https://bisq.network/list-asset, and use blank lines per convention in import statements for the `Mask` class.

2018-11-05 14:22 UTC, diablax commented
squashed

2018-11-05 14:24 UTC, cbeams commented
From https://docs.bisq.network/exchange/howto/list-asset.html#step-5-create-a-well-formed-git-commit:

![image](https://user-images.githubusercontent.com/301810/48003479-d2f71500-e10e-11e8-9e35-11acf711ef4d.png)

2018-11-05 14:40 UTC, diablax commented
My apologies Chris, I have now added the changes.

2018-11-05 14:58 UTC, cbeams requested changes
NACK, per suggested formatting changes.

2018-11-05 14:58 UTC, cbeams commented on assets/src/main/java/bisq/asset/coins/Mask.java
> +
```suggestion
```

2018-11-05 14:58 UTC, cbeams commented on assets/src/test/java/bisq/asset/coins/MaskTest.java
> +	assertInvalidAddress("Wecj8");
```suggestion
        assertInvalidAddress("Wecj8");
```

2018-11-05 14:58 UTC, cbeams commented on assets/src/test/java/bisq/asset/coins/MaskTest.java
> +	assertInvalidAddress("MsopefFnSr4bJFuNoHogCBdDCsqDrNu5Pc1Yh1DfsTUTL5dLbbtE119f4vztxXu6fFCKWRmpqjABdDyGrzMDkhTC38gWw");
```suggestion
        assertInvalidAddress("MsopefFnSr4bJFuNoHogCBdDCsqDrNu5Pc1Yh1DfsTUTL5dLbbtE119f4vztxXu6fFCKWRmpqjABdDyGrzMDkhTC38gWw");
```

2018-11-05 14:58 UTC, cbeams commented on assets/src/test/java/bisq/asset/coins/MaskTest.java
> +	assertInvalidAddress("MeGcanuyt4bJFuNoHogCBdDCsqDrNu5njPc1Yh1DfsTUTL5dLbbtE119f4vztxXu6fFCKWRmpqujABdDyGrzMDkhTC38WwSx");
```suggestion
         assertInvalidAddress("MeGcanuyt4bJFuNoHogCBdDCsqDrNu5njPc1Yh1DfsTUTL5dLbbtE119f4vztxXu6fFCKWRmpqujABdDyGrzMDkhTC38WwSx");
```

2018-11-05 16:04 UTC, diablax commented
Again, apologies. Did not notice these messy lines on nano, perhaps they were formatted differently on my machine.

2018-11-06 11:43 UTC, diablax commented
Let me know if there is anything else to do.

2018-11-06 14:23 UTC, cbeams commented
From https://docs.bisq.network/exchange/howto/list-asset.html#step-6-submit-your-pull-request

![image](https://user-images.githubusercontent.com/301810/48070276-c68abf00-e1d7-11e8-9726-56fd0934e442.png)

The reason I need this is to clean up the body of your commit. You squashed it, but left all the comments from the squashed commits in the body of the remaining commit. The body should be empty. You can do that yourself and force push, or give me rights to do it. I'll merge afterward.

2018-11-07 09:36 UTC, diablax commented
Feel free to amend. Edits are enabled.

2018-11-07 09:47 UTC, diablax commented
Would it be easier to just submit a new PR?

2018-11-07 10:30 UTC, closed without merging

2018-11-07 10:32 UTC, diablax commented
I have cleaned up the code and will resubmit PR to comply with the rules.

2018-11-07 10:33 UTC, cbeams commented
Please just reopen this PR with a force-pushed cleaned up version of your commit. There's no need to open a new PR.

2018-11-07 10:35 UTC, cbeams commented
Wait. This PR now shows 2,085 files changed. Go ahead and resubmit unless you know how to fix that. Note that you submitted this PR from your `master` branch, which is something we ask you not to do in the instructions as well. This may be the source of the problem, especially if you pulled recent changes to upstream master.

2018-11-07 10:37 UTC, cbeams commented
It's because you deleted your fork of the repository.

2018-11-07 10:40 UTC, diablax commented
Yes I will resubmit everything properly and make sure it is on a different branch. Apologies for taking up so much of your time.