Add advanced cash payment method
bisq-network/bisq pull request #1957
Opened 2018-11-23 14:18 UTC by j3ko

closes #1876 and closes #1785

A couple notes about this:

1. In addition to RUB, USD, EUR, GBP as described, Advanced pay also supports UAH, KZT and BRL.  These were included in the currency dropdown as well.
2. All wallet id's follow the form X000000000000 (a letter followed by 12 numbers, confirmed with advanced pay devs) so validation was added for this.

2018-11-23 19:10 UTC, ManfredKarrer requested changes

2018-11-23 19:10 UTC, ManfredKarrer commented on core/src/main/java/bisq/core/payment/AdvancedCashAccount.java
> +        setSingleTradeCurrency(new FiatCurrency("USD"));
`setSingleTradeCurrency` is not correct. Should be like in OKPayAccount: `tradeCurrencies.addAll(CurrencyUtil.getAllOKPayCurrencies());`

2018-11-23 19:10 UTC, ManfredKarrer commented
Great thanks! A small issues is there but rest looks all good!

2018-11-24 06:30 UTC, j3ko commented
Sorry, I was looking at the wrong example payment method when doing this.  

I made some changes to make this more consistent with the OK pay payment method.

2018-11-24 11:08 UTC, ManfredKarrer approved these changes
utACK

2018-11-24 11:09 UTC, merged