List UnitedCommunityCoin (UCC)
bisq-network/bisq pull request #2015
Opened 2018-11-30 16:16 UTC by CaveSpectre11

Official project URL: http://uccnetwork.org/
Official block explorer URL: http://explorer.uccnetwork.org/

2018-12-18 13:15 UTC, blabno requested changes
NACK unknown repository

Also reformat the code

And squash commits into a single one.

2018-12-18 13:15 UTC, blabno commented on assets/src/main/java/bisq/asset/coins/UnitedCommunityCoin.java
> +
Too many newlines

2018-12-18 13:15 UTC, blabno commented on assets/src/main/java/bisq/asset/coins/UnitedCommunityCoin.java
> +
Too many newlines.

2018-12-19 16:21 UTC, ManfredKarrer commented
Open again once "unknown repository" is resolved.

2018-12-19 16:21 UTC, closed without merging