List REOSC Ecosystem (REOSC)
bisq-network/bisq pull request #2133
Opened 2018-12-17 07:58 UTC by REOSC

- Official project URL: [https://www.reosc.io/main.html]
- Official block explorer URL: [https://explorer.reosc.io]

2018-12-18 12:57 UTC, blabno requested changes
NACK per comments

And no PRs from master.

2018-12-18 12:57 UTC, blabno commented on core/src/main/java/bisq/core/locale/CurrencyUtil.java
> +        result.add(new CryptoCurrency("REOSC", "REOSC Ecosystem"));
Do not touch this file.

2018-12-18 12:57 UTC, blabno commented on core/src/test/java/bisq/core/user/PreferencesTest.java
> +        assertEquals(14, preferences.getCryptoCurrenciesAsObservable().size());
Do not touch this file.

2018-12-19 01:21 UTC, REOSC commented
before I posted a commit here, I got the exchange to work on the local network and perform all the transactions. Without a change in the files indicated by you as "do not touch", the exchange did not work.

2018-12-19 10:09 UTC, blabno commented
You clearly don't know what you are doing. Instead of reverting changes in CurrencyUtil you have removed the whole file.

2018-12-19 10:16 UTC, ManfredKarrer commented
Close because of incompetent developers. We don't want to wast our time on such...

2018-12-19 10:16 UTC, closed without merging

2018-12-19 11:11 UTC, REOSC commented
ok, don't "wast"