List Sunplatform (SUNP)
bisq-network/bisq pull request #2146
Opened 2018-12-19 14:23 UTC by sunplatformCore

- Official project URL: https://github.com/sunplatformCore/sunplatform
- Official block explorer URL: http://45.77.13.137/

2018-12-22 03:32 UTC, CaveSpectre11 requested changes
3 of the Invalid Addresses match the regex; as valid addresses:

```
$ egrep -v -e '.*valid [S][a-km-zA-HJ-NP-Z1-9]{24,33}$' addresses.txt
invalid sQEasE1ErGeSSqjruzL879UNPeV7sWbnAN
invalid SfCe8XrgG2

 $ egrep -e '.*valid [S][a-km-zA-HJ-NP-Z1-9]{24,33}$' addresses.txt
valid SQEasE1ErGeSSqjruzL879UNPeV7sWbnAN
valid SRK1eahAugt3k6BQjbR1EFYWTAGzg6uXPd
valid SfCe8XrgG2FTPLyuheJ2kMVTD4QehjPUPb
valid SkSJUTCgfJyGM6REhvt54JNQswnwsGHt5E
invalid SRK1eahBugt3k6BQjbR1EFYWTAGzg6uXpD
invalid SfCe8XrgG2FTPLyuheJ2kMVTD4QehjLULd
invalid SSSJUTCgfJyGM6REhvt54JNQswnwsGHt6e

```

2018-12-22 03:32 UTC, CaveSpectre11 commented on assets/src/test/java/bisq/asset/coins/SUNPTest.java
> +        assertInvalidAddress("SRK1eahBugt3k6BQjbR1EFYWTAGzg6uXpD");
The middle 3 addresses are valid according to your regex

2018-12-23 12:14 UTC, blabno requested changes
NACK
Do not submit code that you have not tested locally!

2018-12-23 12:25 UTC, sunplatformCore commented
I tested in windows it said build succeeded
I run gradlew.bat

On Sun, 23 Dec 2018, 17:44 Bernard Labno <notifications@github.com wrote:

> *@blabno* requested changes on this pull request.
>
> NACK
> Do not submit code that you have not tested locally!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/bisq-network/bisq/pull/2146#pullrequestreview-187618432>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ArewYs-Ue_3Y2YSw9MKCrmLI6RzOXs03ks5u73OSgaJpZM4ZaVz4>
> .
>

2018-12-24 08:54 UTC, closed without merging