List WrkzCoin (WRKZ)
bisq-network/bisq pull request #2147
Opened 2018-12-19 14:48 UTC by wrkzdev

This is a re-submission https://github.com/bisq-network/bisq/pull/1834

- Official project URL: https://www.wrkz.work/
- Official block explorer URL: https://myexplorer.wrkz.work/

2018-12-23 12:10 UTC, blabno requested changes
NACK per comments

2018-12-23 12:10 UTC, blabno commented on assets/src/main/java/bisq/asset/coins/WrkzCoin.java
> +}
Add newline at the end of file

2018-12-23 12:10 UTC, blabno commented on assets/src/test/java/bisq/asset/coins/WrkzCoinTest.java
> +}
Add newline at the end of file

2019-01-07 13:49 UTC, blabno approved these changes
ACK

2019-01-07 14:40 UTC, ripcurlx commented
@wrkzdev Please fix the conflict and I'll merge the PR

2019-01-07 22:44 UTC, merged