List Vidulum (VDL)
bisq-network/bisq pull request #2155
Opened 2018-12-21 02:32 UTC by Corey-Code

- Official project URL: https://Vidulum.app
- Official block explorer URL: https://explorer.vidulum.app

2018-12-23 12:04 UTC, blabno requested changes
NACK per comments

2018-12-23 12:04 UTC, blabno commented on assets/src/main/java/bisq/asset/coins/Vidulum.java
> +        super("Vidulum", "VDL", new VidulumAddressValidator());
Use existing Regex validator

2018-12-28 01:01 UTC, Corey-Code reviewed
fixed as requested

2018-12-28 01:01 UTC, Corey-Code commented on assets/src/main/java/bisq/asset/coins/Vidulum.java
> +        super("Vidulum", "VDL", new VidulumAddressValidator());
done

2018-12-28 02:29 UTC, Corey-Code reviewed
fix test

2019-01-07 13:51 UTC, blabno commented
Tests are failing

2019-01-07 22:41 UTC, ManfredKarrer commented
Close as repeated test fails. Did you ever run the tests?

2019-01-07 22:41 UTC, closed without merging