List Bitzec (BZC)
bisq-network/bisq pull request #2184
Opened 2018-12-29 14:03 UTC by sennevb

- Official project URL:http://bitzec.org

- insight explorer : https://bitzec.insight.equihub.pro

2019-01-07 13:56 UTC, blabno requested changes
NACK per comments

2019-01-07 13:56 UTC, blabno commented on assets/src/main/java/bisq/asset/coins/Bitzec.java
> +        super("Bitzec", "BZC", new BitzecAddressValidator());
Use RegexAddressValidator

2019-02-09 14:14 UTC, bitzec commented
How to fix this

2019-02-17 09:24 UTC, sennevb commented
@blabno code is identical to zcash, so why the regex, it's same as zcash

2019-02-18 06:38 UTC, blabno commented
ZCash had been implemented before Regex validator was introduced.

2019-02-18 08:54 UTC, sennevb commented
Changed to regexvalidator..

2019-02-25 10:55 UTC, blabno commented
@sennevb Code looks good, please squash your commits into a single one (use fixup).

2019-02-25 20:27 UTC, sennevb commented
@blabno can i chat with you somewhere, having diificulties with rebase, used google, but am stuck..

2019-02-26 10:33 UTC, blabno commented
@sennevb https://bisq.slack.com

2019-02-27 11:32 UTC, blabno commented
ACK

2019-02-27 11:32 UTC, blabno approved these changes
ACK

2019-02-27 11:48 UTC, merged