Dao avoid bsq burn
bisq-network/bisq pull request #2242
Opened 2019-01-11 12:55 UTC by sqrrm

2019-01-15 16:12 UTC, sqrrm commented
Regarding Bond.isActive(), I think it's already correct the way it is now.

2019-02-03 15:02 UTC, ManfredKarrer requested changes

2019-02-03 15:02 UTC, ManfredKarrer commented on core/src/main/java/bisq/core/dao/node/parser/TxParser.java
> +                tempTx.setTxType(TxType.UNDEFINED_TX_TYPE);
Not sure if we should use UNDEFINED_TX_TYPE as it does not describe it correctly. Maybe some weaker term than "invalid"? What about NON_STANDARD or "NON_RULED_COMFORM"?

2019-02-03 15:02 UTC, ManfredKarrer commented on core/src/main/java/bisq/core/dao/governance/bond/Bond.java
> +        return bondState == BondState.LOCKUP_TX_CONFIRMED ||
I think UNLOCK_TX_PENDING is missing

2019-02-03 15:02 UTC, ManfredKarrer commented on core/src/main/resources/i18n/displayStrings.properties
> +dao.wallet.receive.bsqAddress=BSQ wallet address (This is a new unused address to avoid address reuse, \
That is quite verbose. What about:
Fresh unused BSQ wallet address

2019-02-03 15:19 UTC, sqrrm commented on core/src/main/java/bisq/core/dao/node/parser/TxParser.java
> +                tempTx.setTxType(TxType.UNDEFINED_TX_TYPE);
If we add another type we can, this was an attempt to avoid adding more txTypes.

2019-02-03 15:22 UTC, sqrrm commented on core/src/main/java/bisq/core/dao/governance/bond/Bond.java
> +        return bondState == BondState.LOCKUP_TX_CONFIRMED ||
It's here, next line down.

2019-02-03 15:42 UTC, sqrrm commented on core/src/main/resources/i18n/displayStrings.properties
> +dao.wallet.receive.bsqAddress=BSQ wallet address (This is a new unused address to avoid address reuse, \
I shortened in a later commit

2019-02-03 20:11 UTC, ManfredKarrer commented on core/src/main/java/bisq/core/dao/node/parser/TxParser.java
> +                tempTx.setTxType(TxType.UNDEFINED_TX_TYPE);
I think IRREGULAR might be a good type for not-rule-conform but still valid txs.

2019-02-03 21:05 UTC, sqrrm commented on core/src/main/java/bisq/core/dao/node/parser/TxParser.java
> +                tempTx.setTxType(TxType.UNDEFINED_TX_TYPE);
Yeah, let's do that to show it's parsed and something is not right but it's still a valid BSQ tx in some way.

2019-02-03 21:59 UTC, merged