List CloakCoin (CLOAK)
bisq-network/bisq pull request #2326
Opened 2019-01-28 03:36 UTC by anorakthagreat

- Official project URL: https://www.cloakcoin.com
- Official block explorer URL: https://chainz.cryptoid.info/cloak/

2019-02-07 07:54 UTC, blabno requested changes
NACK per comments

2019-02-07 07:54 UTC, blabno commented on assets/src/main/java/bisq/asset/coins/CloakCoin.java
> +/*    public static class CloakCoinParams extends NetworkParametersAdapter
Remove this rubish.

2019-02-07 07:54 UTC, blabno commented on assets/src/main/java/bisq/asset/coins/CloakCoin.java
> +        public CloakCoinAddressValidator() {
No need for such a constructor.

2019-02-07 07:54 UTC, blabno commented on assets/src/main/java/bisq/asset/coins/CloakCoin.java
> +            if (!address.matches("^[B|C][a-km-zA-HJ-NP-Z1-9]{33}$") && !address.matches("^smY[a-km-zA-HJ-NP-Z1-9]{99}$"))
This is pure regex validation and does not use anything from super class, so just use `RegexAddressValidator` instead of creating your own validator.

2019-02-07 07:55 UTC, blabno commented
Provide link to a regular transaction (not block reward) in your block explorer that would allow us to determine if arbitration will be possible.

2019-02-07 18:17 UTC, anorakthagreat commented
> Provide link to a regular transaction (not block reward) in your block explorer that would allow us to determine if arbitration will be possible.

https://chainz.cryptoid.info/cloak/tx.dws?5114137.htm

2019-02-18 06:41 UTC, blabno commented
Please squash commits into a single one. Code looks good.

2019-02-18 17:40 UTC, anorakthagreat commented
Done.

2019-02-27 11:49 UTC, merged