List Augmint Euro (AEUR)
bisq-network/bisq pull request #2345
Opened 2019-01-30 17:11 UTC by phraktle

- Official project URL: https://www.augmint.org
- Official block explorer URL: N/A since it's an ERC-20 token, not a coin. The token contract is at: https://etherscan.io/token/0xc994a2dEb02543Db1f48688438b9903c4b305ce3

2019-02-05 09:58 UTC, ripcurlx requested changes
Being a little bit picky, but please rename your commit message to `List Augmint Euro (AEUR)` instead of `List Augmint Euro ([AEUR])` (see https://docs.bisq.network/exchange/howto/list-asset.html#step-5-create-a-well-formed-git-commit).
Besides that ACK from my side.

2019-02-05 10:07 UTC, phraktle commented
Commit message fixed, thanks @ripcurlx!

2019-02-05 10:08 UTC, phraktle commented
Btw, shouldn't ERC-20 tokens specify the token contract's address somewhere? I guess there's no usage of this in Bisq currently, but it could be useful on the UI.

2019-02-05 10:11 UTC, ripcurlx approved these changes

2019-02-05 10:11 UTC, merged

2019-02-05 10:11 UTC, ripcurlx commented
It is not a requirement IMHO if you just want to trade it. Just merged your PR.

2019-02-05 10:14 UTC, phraktle commented
Sure, it's just potentially very helpful for all parties involved (the recipient and in case of a dispute, the arbitrator needs to know definitively what the token address was supposed to be, so they are receiving the appropriate token, not something else named the same).

2019-02-05 10:27 UTC, ripcurlx commented
> Sure, it's just potentially very helpful for all parties involved (the recipient and in case of a dispute, the arbitrator needs to know definitively what the token address was supposed to be, so they are receiving the appropriate token, not something else named the same).

true - @ManfredKarrer Would it be a problem if we add the token address as another property to the ERC20Token class? This is not serialized as a ProtoBuffer message anyways, correct? Of course this would in the end also needed to be added in the trade process, in trade details,... as well. Could be a bounty that we put out to be taken.

2019-02-05 10:30 UTC, ManfredKarrer commented
@ripcurlx I don't see a problem to add that to the ERC20Token class

2019-02-06 15:16 UTC, phraktle commented
If you do decide to add this, the token address for AEUR is `0xc994a2dEb02543Db1f48688438b9903c4b305ce3`