Seed node repo refactoring
bisq-network/bisq pull request #2464
Opened 2019-02-25 15:08 UTC by freimair

github.com/AlDanial/cloc v 1.80  T=0.07 s (14.0 files/s, 14.0 lines/s)

_ | files | blank | comment | code
:-------|-------:|-------:|-------:|-------:
 same|0|0|98|645
 modified|5|0|0|20
 added|1|18|22|57
 removed|7|97|145|321

2019-02-25 15:42 UTC, ManfredKarrer requested changes

2019-02-25 15:42 UTC, ManfredKarrer commented on core/src/test/resources/testnet.seednodes
> +# nodeaddress.onion:port [(@owner)]
They are all removed. Better not have them in the code otherwise people think they are running.

2019-02-27 18:17 UTC, ManfredKarrer approved these changes
utACK

2019-02-27 18:18 UTC, merged

2019-02-27 19:33 UTC, ManfredKarrer commented
@freimair I reverted that PR as I had issues with seednodes when using it. Can you please have a look and open a new PR with that content and tested with existing seed node setup (usual prog args).

2019-02-28 08:58 UTC, freimair commented
https://github.com/bisq-network/bisq/commit/a9ee15d9f60b52d0c5e2e3a9cc24e9be82a8b407#commitcomment-32515049

2019-02-28 15:00 UTC, freimair commented
nevermind: https://github.com/bisq-network/bisq/pull/2476

shame on me