Seed node repo refactoring
bisq-network/bisq pull request #2476
Opened 2019-02-28 12:12 UTC by freimair

shame on me...

2019-03-01 22:50 UTC, ManfredKarrer commented
@ripcurlx Lets delay that after release so we keep test efforts low.

2019-03-06 23:02 UTC, ManfredKarrer requested changes
If I use a localhost seed node it tries to connect to one of the onion addresses.

`We send a PreliminaryGetDataRequest to peer rxdkppp3vicnbgqt.onion:8002. `

Seems the handling for localhost is missing something.

2019-03-06 23:05 UTC, ManfredKarrer commented
Are the duplicated resources in the test/resource directory needed? Might cause consfusion...

2019-03-06 23:07 UTC, ManfredKarrer commented
With a dev DAO_TESTNET seed it worked. Have not tested yet with the live seeds....

2019-03-07 11:48 UTC, freimair commented
> If I use a localhost seed node it tries to connect to one of the onion addresses.

how do you specify that you want to use a localhost seed node?

> Are the duplicated resources in the test/resource directory needed?

for testing. tests do not have access to the main resources.

2019-03-07 16:31 UTC, ManfredKarrer approved these changes
NACK Cannot get localhost dev setup running.

2019-03-07 16:31 UTC, ManfredKarrer commented on core/src/main/resources/btc_regtest.seednodes
> +# 1. Run a seed node with prog args: --bitcoinNetwork=regtest --nodePort=8002 --appName=bisq_seed_node_localhost_8002
should be 2002 -> I edited it already...

2019-03-07 21:46 UTC, ManfredKarrer commented
Dman, my #d9f9baf commit done on GH has committed to Bisq master instead to your PR. So I will merge now and try to find the issue why localhost is not working....

2019-03-07 21:46 UTC, merged

2019-03-08 14:28 UTC, freimair commented
ahm ok, but are you sure? I see your commit in my branch...

2019-03-08 17:25 UTC, ManfredKarrer commented
Don't know exactly what went wrong....