Bisq Listing
bisq-network/bisq pull request #2520
Opened 2019-03-09 16:29 UTC by hooftly

Block Explorer to check transactions is located [Here](https://explorer.getamitycoin.org/ex2/index.html)

https://explorer.getamitycoin.org/ex2/index.html

2019-03-11 07:18 UTC, blabno requested changes
NACK invalid commit message and PR description. Read asset listing guidelines before submitting PRs.

The code looks good. Needs just a codestyle touch.

2019-03-11 07:18 UTC, blabno commented on assets/src/main/java/bisq/asset/coins/Amitycoin.java
> +}
Make sure to add newlines at the end of each file.

2019-03-11 07:18 UTC, blabno commented on assets/src/test/java/bisq/asset/coins/AmitycoinTest.java
> +}
Make sure to add newlines at the end of each file.

2019-03-11 10:20 UTC, hooftly commented
I will start again apologies.

2019-03-11 10:39 UTC, blabno commented
Please reuse this PR, just reopen it and push with force amended commit.

2019-03-11 11:09 UTC, hooftly commented
Understood

On Mon., Mar. 11, 2019, 4:39 a.m. Bernard Labno, <notifications@github.com>
wrote:

> Please reuse this PR, just reopen it and push with force amended commit.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/bisq-network/bisq/pull/2520#issuecomment-471488539>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/Ann9MXktIJQwbFJ5qVS17I8g1E1uzBNSks5vVjJ1gaJpZM4bmxKE>
> .
>

2019-03-11 16:11 UTC, hooftly commented
Let me know if I bungled this up.

2019-03-12 00:45 UTC, hooftly commented
Can I close this and try again?  Apologies for the mess

2019-03-12 08:10 UTC, blabno commented
Grant me the access to your fork and I'll clean this up.

2019-03-12 12:03 UTC, hooftly commented
Access Granted.

2019-03-13 10:18 UTC, blabno approved these changes
ACK

2019-03-16 15:40 UTC, merged