Add checkbox to hide extreme offers in chart
bisq-network/bisq pull request #2884
Opened 2019-06-14 12:10 UTC by sqrrm

2019-06-14 12:59 UTC, mrosseel commented
since no issue is linked I'll comment here, is this the final solution? Other solutions would be a log scale, or an algorithm to cut off offers which are too far away. Available to brain-storm that algorithm ;)

2019-06-14 17:24 UTC, sqrrm commented
@mrosseel  Not much thought went into this. I just got annoyed with the BSQ market chart being unusable. This solution hides the extreme offers from the chart (more than a factor 5 from the best offers). I don't really want to put much more work into this right now, which the log scale solution probably would be.

2019-06-14 18:29 UTC, HarryMacfinned commented
Thanks @sqrrm ,
btw, this extreme offers seems really here to intentionally damage.
Sometimes it briefly disappears ... and some hours later they are here again.

2019-06-20 07:55 UTC, ripcurlx requested changes
I personally would just remove the extremes without adding new controls as I don't think there is a use case where someone wants to have this kind of display. If we find time in the future to adapt to a logarithmic scale or similar we can just adapt the code again. Besides that ACK.

2019-06-20 10:14 UTC, sqrrm commented
Removed the checkbox. There is no indication that some offers might not be displayed in the chart now, but I suppose that's ok, it's about usability, not correctness.

2019-06-21 08:43 UTC, ripcurlx commented
> Removed the checkbox. There is no indication that some offers might not be displayed in the chart now, but I suppose that's ok, it's about usability, not correctness.

Yes, I understand your concerns, but we had a similar solution in place before (only display the best offers at all), so I think it is OK if we continue to iterate on this over time.

2019-06-21 08:47 UTC, ripcurlx requested changes
Please have a look at my comments.

2019-06-21 08:47 UTC, ripcurlx commented on core/src/main/resources/i18n/displayStrings.properties
> +shared.hideExtremes=Hide extremes
Please remove the translation as well

2019-06-21 08:47 UTC, ripcurlx commented on desktop/src/main/java/bisq/desktop/main/market/offerbook/OfferBookChartView.java
> +        GridPane topGrid = new GridPane();
Please also remove the additional GridPane again, so we don't use more containers as necessary.

2019-06-21 10:03 UTC, sqrrm commented
Removed all the extras except for the column option to a checkbox in FormBuilder.

2019-07-12 08:33 UTC, ripcurlx approved these changes

2019-07-12 08:33 UTC, merged