List SixEleven (611)
bisq-network/bisq pull request #2892
Opened 2019-06-17 23:05 UTC by fflo

- Official project URL: https://611project.org && https://github.com/611project/sixeleven
- Official block explorer: https://be.611.to

Link to random transaction (1):
https://be.611.to/block/6d5793cc5f06f4a6748f970cc3871078dce185a75ec2f408f885c23c7a2a76f8
Link to random transaction (2):
https://be.611.to/block/ae9a344381e7f735939df2f0834e00d09c043fd67aa74042b00ced76abe12a38

2019-06-24 00:47 UTC, fflo commented
update Namecoin (NMC) AddressValidator with new Base58BitcoinAddressValidator ...

2019-07-09 07:40 UTC, blabno commented
Just one asset per PR please.

2019-07-13 04:55 UTC, fflo commented
ok, everything squashed together into one commit.

2019-07-15 12:12 UTC, blabno commented
Just one asset per PR please.

2019-07-20 11:31 UTC, fflo commented
Thx.

2019-07-22 09:16 UTC, blabno requested changes
NACK per comments

2019-07-22 09:16 UTC, blabno commented on core/src/main/java/bisq/core/locale/CurrencyUtil.java
> +        result.add(new CryptoCurrency("SIL", "SixEleven"));
Don't touch this file.

2019-07-24 22:39 UTC, fflo commented
Thx.

2019-07-30 07:59 UTC, blabno approved these changes
ACK

2019-07-30 08:08 UTC, merged