List Vertcoin (VTC)
bisq-network/bisq pull request #2901
Opened 2019-06-19 00:43 UTC by cruelnovo

Author: Matt Cummings <matt@gocummings.com>
Date: Tue Jun 18 20:36:00 2019 -0500

     List Vertcoin (VTC)

2019-06-19 00:48 UTC, cruelnovo commented
- Official project URL: https://verticoin.org/
- Official block explorer URL: https://insight.vertcoin.org/

2019-07-09 07:48 UTC, blabno requested changes
NACK per comments.

Apart from that code looks good.

2019-07-09 07:48 UTC, blabno commented on assets/src/main/java/bisq/asset/coins/Vertcoin.java
> +        super("Vertcoin", "VTC", new Base58BitcoinAddressValidator(new VertcoinMainNetParams()), Network.MAINNET);
`Network.MAINNET` is default so remove it.

2019-07-15 12:13 UTC, blabno commented
Squash the commits into a single on, keeping the message from the first commit.

2019-07-17 09:21 UTC, blabno approved these changes
ACK

2019-07-17 09:21 UTC, merged