also fix singleton config for core module
bisq-network/bisq pull request #3061
Opened 2019-08-07 09:57 UTC by christophsturm

follow up to #3058 that converts the core module too. 
and unit test it all

2019-08-07 12:28 UTC, blabno approved these changes
The code looks good.
I see pros and cons in both approaches. Just as forgetting to configure class as singleton in a module you can forget about annotating the class. Defining life cycle inside module allows for class reuse in different context, but that's very theoretical benefit.

2019-08-13 13:26 UTC, sqrrm requested changes
Please fix the missing singleton

2019-08-13 13:26 UTC, sqrrm commented on core/src/main/java/bisq/core/CoreModule.java
> -        bind(MobileMessageEncryption.class).in(Singleton.class);
MobileMessageEncryption doesn't have singleton annotation and not tested in GuiceSetupTest.java

2019-08-13 14:05 UTC, sqrrm approved these changes
utACK

2019-08-13 14:06 UTC, merged