feature jdk10 instructions more prominently
bisq-network/bisq pull request #3079
Opened 2019-08-13 14:41 UTC by christophsturm

since it keeps coming up in the dev channel

2019-08-13 16:07 UTC, freimair requested changes

2019-08-13 16:07 UTC, freimair commented on README.md
> +<<<<<<< Updated upstream
```suggestion
```

2019-08-14 15:07 UTC, ManfredKarrer approved these changes
utACK

2019-08-14 15:22 UTC, freimair approved these changes
utAck

2019-08-14 15:22 UTC, merged