Refactor checkMaxConnections
bisq-network/bisq pull request #3126
Opened 2019-08-22 07:22 UTC by devinbileck

Fix connection limit checks so as to prevent the following warning:

> WARN  b.n.p2p.peers.PeerManager: No candidates found to remove (That
case should not be possible as we use in the last case all
connections).

2019-08-22 08:57 UTC, mrosseel commented
this might be a good opportunity to add a unit test for PeerManager (possibly limited to the scope of connection handling)

2019-08-22 17:42 UTC, ripcurlx submitted a review, later dismissed
utACK

2019-08-22 20:43 UTC, devinbileck commented
> this might be a good opportunity to add a unit test for PeerManager (possibly limited to the scope of connection handling)

It seems the PeerManagerTest is ignored and in need of an overhaul.

2019-08-27 07:47 UTC, ripcurlx commented
Could someone of the exisiting contributors try out this branch before merging, as it would cause big problems if some use-case handling is wrong. I just read through the code and it looks fine, but it would be good to give this a local test as well.

2019-08-27 17:47 UTC, ManfredKarrer commented
I think that code part is really a good candidate for a test. The logic is a bit involved and bigger changes here are tough to test manually. I would postpone otherwise merge until someone had dedicated enough time to be sure all is correct.

2019-08-27 19:33 UTC, devinbileck commented
Agreed. I will try to look into implementing some tests. Just not familiar with this area so will need some time to ramp up.

2019-09-19 13:46 UTC, ripcurlx commented
> Agreed. I will try to look into implementing some tests. Just not familiar with this area so will need some time to ramp up.

@devinbileck Are you still on this PR?

2019-09-19 18:51 UTC, devinbileck commented
I started looking into it but didn't make much progress. I haven't focused on it very much lately. If someone else is able to contribute something, feel free. Otherwise I will try to get to it.

2019-11-12 10:27 UTC, ripcurlx commented
@devinbileck Could you please resolve the conflict and add some tests?
@freimair Could you review the code?

2019-11-12 16:32 UTC, devinbileck commented
I have added some tests. I will be committing them shortly.

2019-11-13 20:44 UTC, devinbileck commented
@ripcurlx @freimair ready for review.

2019-11-14 14:49 UTC, ripcurlx commented
@freimair As I haven't touched this part of the codebase so far, could you please do the review? Thanks!

2019-11-18 12:09 UTC, freimair requested changes
IMO we could get away with mocking the `SeedNodeRepository` superclass, thus eliminating the dependency to `core`. Can you verify that this is correct?

2019-11-18 12:09 UTC, freimair commented on build.gradle
> +        testCompile project(':core')
```suggestion

```

2019-11-18 12:09 UTC, freimair commented on p2p/src/test/java/bisq/network/p2p/MockNode.java
> +import bisq.core.network.p2p.seed.DefaultSeedNodeRepository;
```suggestion
import bisq.network.p2p.seed.SeedNodeRepository;
```

2019-11-18 12:09 UTC, freimair commented on p2p/src/test/java/bisq/network/p2p/MockNode.java
> +        peerManager = new PeerManager(networkNode, mock(DefaultSeedNodeRepository.class), new ClockWatcher(), maxConnections, storage);
```suggestion
        peerManager = new PeerManager(networkNode, mock(SeedNodeRepository.class), new ClockWatcher(), maxConnections, storage);
```

2019-11-21 00:31 UTC, devinbileck commented
Yes, good point. Updated!

2019-11-26 13:51 UTC, freimair approved these changes

2019-11-26 14:16 UTC, merged