Set active currencies as high chargeback risk
bisq-network/bisq pull request #3164
Opened 2019-08-29 22:59 UTC by sqrrm

Specify the currencies that are considered high risk for chargeback based on volume. As new markets grow we will probably have to add them as well, but it might be that some currencies don't have as much chargeback risk.

By allowing new markets to trade without any restrictions they get a chance to grow without too much pain of bootstrapping signed account witnesses.

2019-08-29 23:25 UTC, ManfredKarrer approved these changes
utACK

2019-08-30 00:15 UTC, huey735 commented
If the AUD market is in that list so should the BRL as it has been more active recently, and If I'm not wrong already surpassed AUD in trade numbers and volume.

What is the list of payment methods that remain under this limit list?

2019-08-30 09:13 UTC, ripcurlx commented
> If the AUD market is in that list so should the BRL as it has been more active recently, and If I'm not wrong already surpassed AUD in trade numbers and volume.
> 
> What is the list of payment methods that remain under this limit list?

True - the AUD/BTC market is not as big as the BRL right now.

AUD/BTC
![Bildschirmfoto 2019-08-30 um 11 07 38](https://user-images.githubusercontent.com/170962/64008515-915cae00-cb16-11e9-932c-f4a966e69356.png)

BRL/BTC
![Bildschirmfoto 2019-08-30 um 11 07 47](https://user-images.githubusercontent.com/170962/64008531-99b4e900-cb16-11e9-9ad0-bca372005a57.png)

@ManfredKarrer Do you remember if we had scam issues in the AUD market already?
If not, I agree with @huey735 that we might not need to add AUD as well or add BRL if we have the feeling that it might be too risky to exclude it from our current limit.

@huey735 As most limited payment methods only support one currency (e.g. EUR, USD) the ones that have this multiple currency options and are limited right now are:  National bank transfer, same bank transfer, specific bank transfer, Revolut and Uphold.

2019-08-30 10:33 UTC, ManfredKarrer commented
I would prefer to be cautious than sorry. So maybe add BRL as well as it has significantly enough volume for a scammer to be targeted.

2019-08-30 10:54 UTC, ripcurlx commented
> I would prefer to be cautious than sorry. So maybe add BRL as well as it has significantly enough volume for a scammer to be targeted.

@sqrrm Could you add BRL to the list of countries as well?

2019-08-30 10:55 UTC, ripcurlx requested changes
NACK - Please add BRL as well as suggested by @huey735

2019-08-30 12:04 UTC, ripcurlx approved these changes

2019-08-30 12:05 UTC, merged