Integrate PhoneNumberValidator into HalCashForm
bisq-network/bisq pull request #3236
Opened 2019-09-10 15:16 UTC by ghubstan

Added country selector to HalCashForm, requiring the following changes.

1.  A new CountryUtil method getAllHalCashCountries, returns [ES, PL].
2.  HalCashValidator now extends PhoneNumberValidator.
3.  HalCashAccountPayload now extends CountryBasedPaymentAccountPayload.
4.  HalCashAccount now extends CountryBasedPaymentAccount.
5.  Added two new fields to pb.proto.
    a.  HalCashAccountPayload hal_cash_account_payload field to
        CountryBasedPaymentAccountPayload message.
    b.  accepted_country_codes field to HalCashAccountPayload message.
    Note:  pb.proto changes may break backward compatibility.
6.  Reformatted all modified source files except pb.proto.

This patch is part of solution to Issue #3042.

2019-09-19 16:08 UTC, ripcurlx requested changes
NACK - I think it is not a good idea to add the account creation validation and push it as far to invalidate all existing HalCash accounts for offers created with phone number validated HalCash accounts. Doing it like that it would also force people with correct phone numbers to create a new account and loose their account age. I think it is better for this PR only to add the phone number validation in the account creation form and leave everything else as is.

2019-09-19 16:11 UTC, ripcurlx commented
As it is implemented right now, it is as if we are introducing two new payment methods. HalCash (ES) and HalCash (PL). Also I'm not sure if it is maybe also possible to transfer money with HalCash between ES and PL.

2019-09-20 15:10 UTC, ghubstan commented
It is clear you can send international remittances to an halcash networked ATM in other countries.
https://www.halcash.com/es/usos   (See "REMESAS")

It is not clear halcash users can transfer fiat from one bank account to another, so I think it should be assumed to not be possible.

2019-09-20 15:10 UTC, ghubstan commented
@ripcurlx, Thanks for the feedback.   I'll revert protobuf changes to limit validation to the create payment method use case.

Phone validation depends on country.  How would you suggest I add a country selector without implying the payment method can be used to transfer fiat between Spain and Poland?

2019-09-20 15:40 UTC, ripcurlx commented
If it is not possible to send it across borders than the old implementation was false in that regard and what you came up with is the correct implementation. I’ll think about the best case migration scenario.

2019-09-20 17:51 UTC, ghubstan commented
According to [this EN site](https://affgambler.com/banking/halcash-casinos), recipients  _need a cell phone_ (not email), and access to any HalCash ATM in Spain or Poland.   Money can be sent across borders, is not deposited in the recipient's bank account, and  HalCash ATM withdrawal limits apply.

> To send money users should have a bank account with one of participating institutions. In this case they will need to provide phone number of the receiver, PIN code and specify how much money they want to send. Once all required information is sent, receiver gets an SMS telling a reference code. It takes few moments for money transfer to be processed, and withdrawal is possible just seconds later.

> After getting a message about money transfer, users should find closest HalCash ATM. There will be “Withdrawal without using a card” option on a display. Select it and then push HalCash button to find simple instructions you should follow. If you are trying to withdraw money, you’ll need to enter your phone number, transfer size, reference code and PIN code. The latter should be provided by a sender. If the information is accurate, you’ll receive cash.

According to this [HalCash FAQ](https://www.halcash.com/en/quienes-somos/), there are plans to add US ATM and POS systems to the network.

2019-11-12 11:46 UTC, ripcurlx commented
> It is clear you can send international remittances to a halcash networked ATM in other countries.
> https://www.halcash.com/es/usos (See "REMESAS")

But isn't that our use case? So someone wants to buy BTC with Halcash and sends the code to the phonenumber of the recipient. The recipient goes to a Halcash ATM receiveds the money and releases the BTC. To make that possible we shouldn't split up Halcash on a country basis, but just validate a general phone number on creation or leave it as it is right now.

2019-11-16 18:19 UTC, ghubstan commented
Leaving it as is and closing PR.

2019-11-16 18:19 UTC, closed without merging