Fixed sorting in views with TableView instances with no implemented sort
bisq-network/bisq pull request #3319
Opened 2019-09-24 04:33 UTC by niyid

Issue #3231

2019-11-01 08:02 UTC, freimair requested changes
@niyid thanks for your contribution. However, when I try to run your stuff, I get exception windows popping up for every view that has a table in it. Would you mind having a look again?

```
Nov-01 08:54:48.977 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: Uncaught Exception from thread JavaFX Application Thread 
Nov-01 08:54:48.977 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: throwableMessage= Duplicate TableColumns detected in TableView columns list with titles 'null',  
Nov-01 08:54:48.978 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: throwableClass= class java.lang.IllegalStateException 
Nov-01 08:54:48.979 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: Stack trace:
java.lang.IllegalStateException: Duplicate TableColumns detected in TableView columns list with titles 'null', 
	at javafx.scene.control.TableView$5.onChanged(TableView.java:636)
	at javafx.collections.WeakListChangeListener.onChanged(WeakListChangeListener.java:88)
	at com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(ListListenerHelper.java:164)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at javafx.collections.ModifiableObservableListBase.add(ModifiableObservableListBase.java:155)
	at java.base/java.util.AbstractList.add(AbstractList.java:111)
	at bisq.desktop.main.market.offerbook.OfferBookChartView.getOfferTable(OfferBookChartView.java:614)
	at bisq.desktop.main.market.offerbook.OfferBookChartView.initialize(OfferBookChartView.java:159)
	at bisq.desktop.common.view.InitializableView.initialize(InitializableView.java:41)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2573)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2466)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2435)
	at bisq.desktop.common.fxml.FxmlViewLoader.loadFromFxml(FxmlViewLoader.java:101)
	at bisq.desktop.common.fxml.FxmlViewLoader.load(FxmlViewLoader.java:90)
	at bisq.desktop.common.view.CachingViewLoader.load(CachingViewLoader.java:41)
	at bisq.desktop.main.market.MarketView.loadView(MarketView.java:159)
	at bisq.desktop.main.market.MarketView.lambda$initialize$0(MarketView.java:100)
	at bisq.desktop.Navigation.lambda$navigateTo$1(Navigation.java:140)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:804)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	at bisq.desktop.Navigation.navigateTo(Navigation.java:140)
	at bisq.desktop.Navigation.navigateTo(Navigation.java:104)
	at bisq.desktop.main.market.MarketView.activate(MarketView.java:135)
	at bisq.desktop.common.view.ActivatableViewAndModel.lambda$prepareInitialize$0(ActivatableViewAndModel.java:43)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:74)
	at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
	at javafx.scene.Node$ReadOnlyObjectWrapperManualFire.fireSuperValueChangedEvent(Node.java:1054)
	at javafx.scene.Node.invalidatedScenes(Node.java:1114)
	at javafx.scene.Node.setScenes(Node.java:1152)
	at javafx.scene.Parent$2.onChanged(Parent.java:369)
	at com.sun.javafx.collections.TrackableObservableList.lambda$new$0(TrackableObservableList.java:45)
	at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
	at javafx.collections.ModifiableObservableListBase.setAll(ModifiableObservableListBase.java:90)
	at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:116)
	at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:108)
	at bisq.desktop.main.MainView.lambda$initialize$7(MainView.java:376)
	at bisq.desktop.Navigation.lambda$navigateTo$1(Navigation.java:140)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:804)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	at bisq.desktop.Navigation.navigateTo(Navigation.java:140)
	at bisq.desktop.Navigation.navigateToPreviousVisitedView(Navigation.java:155)
	at bisq.desktop.main.MainView.lambda$initialize$9(MainView.java:393)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.beans.property.BooleanPropertyBase.fireValueChangedEvent(BooleanPropertyBase.java:104)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:111)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
	at bisq.desktop.main.MainViewModel.onSetupComplete(MainViewModel.java:252)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1378)
	at bisq.core.app.BisqSetup.step5(BisqSetup.java:331)
	at bisq.core.app.BisqSetup.lambda$startP2pNetworkAndWallet$9(BisqSetup.java:547)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.beans.binding.ObjectBinding.invalidate(ObjectBinding.java:170)
	at com.sun.javafx.binding.BindingHelperObserver.invalidated(BindingHelperObserver.java:52)
	at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:136)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
	at javafx.beans.property.BooleanPropertyBase.fireValueChangedEvent(BooleanPropertyBase.java:104)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:111)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
	at bisq.core.app.P2PNetworkSetup$2.onDataReceived(P2PNetworkSetup.java:163)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at bisq.network.p2p.P2PService.onDataReceived(P2PService.java:359)
	at bisq.network.p2p.peers.getdata.RequestDataManager$2.onComplete(RequestDataManager.java:339)
	at bisq.network.p2p.peers.getdata.RequestDataHandler.onMessage(RequestDataHandler.java:282)
	at bisq.network.p2p.network.NetworkNode.lambda$onMessage$4(NetworkNode.java:357)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at bisq.network.p2p.network.NetworkNode.onMessage(NetworkNode.java:357)
	at bisq.network.p2p.network.Connection.lambda$onMessage$5(Connection.java:429)
	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:804)
	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
	at bisq.network.p2p.network.Connection.lambda$onMessage$6(Connection.java:429)
 [...]

2019-11-01 08:23 UTC, niyid commented
OK. Will do. Apologies for that.

On Fri, Nov 1, 2019, 09:02 Florian Reimair <notifications@github.com> wrote:

> *@freimair* requested changes on this pull request.
>
> @niyid <https://github.com/niyid> thanks for your contribution. However,
> when I try to run your stuff, I get exception windows popping up for every
> view that has a table in it. Would you mind having a look again?
>
> Nov-01 08:54:48.977 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: Uncaught Exception from thread JavaFX Application Thread
> Nov-01 08:54:48.977 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: throwableMessage= Duplicate TableColumns detected in TableView columns list with titles 'null',
> Nov-01 08:54:48.978 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: throwableClass= class java.lang.IllegalStateException
> Nov-01 08:54:48.979 [JavaFX Application Thread] ERROR bisq.common.setup.CommonSetup: Stack trace:
> java.lang.IllegalStateException: Duplicate TableColumns detected in TableView columns list with titles 'null',
> 	at javafx.scene.control.TableView$5.onChanged(TableView.java:636)
> 	at javafx.collections.WeakListChangeListener.onChanged(WeakListChangeListener.java:88)
> 	at com.sun.javafx.collections.ListListenerHelper$SingleChange.fireValueChangedEvent(ListListenerHelper.java:164)
> 	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
> 	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
> 	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
> 	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
> 	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
> 	at javafx.collections.ModifiableObservableListBase.add(ModifiableObservableListBase.java:155)
> 	at java.base/java.util.AbstractList.add(AbstractList.java:111)
> 	at bisq.desktop.main.market.offerbook.OfferBookChartView.getOfferTable(OfferBookChartView.java:614)
> 	at bisq.desktop.main.market.offerbook.OfferBookChartView.initialize(OfferBookChartView.java:159)
> 	at bisq.desktop.common.view.InitializableView.initialize(InitializableView.java:41)
> 	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2573)
> 	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2466)
> 	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2435)
> 	at bisq.desktop.common.fxml.FxmlViewLoader.loadFromFxml(FxmlViewLoader.java:101)
> 	at bisq.desktop.common.fxml.FxmlViewLoader.load(FxmlViewLoader.java:90)
> 	at bisq.desktop.common.view.CachingViewLoader.load(CachingViewLoader.java:41)
> 	at bisq.desktop.main.market.MarketView.loadView(MarketView.java:159)
> 	at bisq.desktop.main.market.MarketView.lambda$initialize$0(MarketView.java:100)
> 	at bisq.desktop.Navigation.lambda$navigateTo$1(Navigation.java:140)
> 	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:804)
> 	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
> 	at bisq.desktop.Navigation.navigateTo(Navigation.java:140)
> 	at bisq.desktop.Navigation.navigateTo(Navigation.java:104)
> 	at bisq.desktop.main.market.MarketView.activate(MarketView.java:135)
> 	at bisq.desktop.common.view.ActivatableViewAndModel.lambda$prepareInitialize$0(ActivatableViewAndModel.java:43)
> 	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
> 	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
> 	at javafx.beans.property.ReadOnlyObjectPropertyBase.fireValueChangedEvent(ReadOnlyObjectPropertyBase.java:74)
> 	at javafx.beans.property.ReadOnlyObjectWrapper.fireValueChangedEvent(ReadOnlyObjectWrapper.java:102)
> 	at javafx.scene.Node$ReadOnlyObjectWrapperManualFire.fireSuperValueChangedEvent(Node.java:1054)
> 	at javafx.scene.Node.invalidatedScenes(Node.java:1114)
> 	at javafx.scene.Node.setScenes(Node.java:1152)
> 	at javafx.scene.Parent$2.onChanged(Parent.java:369)
> 	at com.sun.javafx.collections.TrackableObservableList.lambda$new$0(TrackableObservableList.java:45)
> 	at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
> 	at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
> 	at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:233)
> 	at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
> 	at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
> 	at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:205)
> 	at javafx.collections.ModifiableObservableListBase.setAll(ModifiableObservableListBase.java:90)
> 	at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:116)
> 	at com.sun.javafx.collections.VetoableListDecorator.setAll(VetoableListDecorator.java:108)
> 	at bisq.desktop.main.MainView.lambda$initialize$7(MainView.java:376)
> 	at bisq.desktop.Navigation.lambda$navigateTo$1(Navigation.java:140)
> 	at java.base/java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:804)
> 	at java.base/java.util.concurrent.CopyOnWriteArraySet.forEach(CopyOnWriteArraySet.java:425)
> 	at bisq.desktop.Navigation.navigateTo(Navigation.java:140)
> 	at bisq.desktop.Navigation.navigateToPreviousVisitedView(Navigation.java:155)
> 	at bisq.desktop.main.MainView.lambda$initialize$9(MainView.java:393)
> 	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
> 	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
> 	at javafx.beans.property.BooleanPropertyBase.fireValueChangedEvent(BooleanPropertyBase.java:104)
> 	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:111)
> 	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
> 	at bisq.desktop.main.MainViewModel.onSetupComplete(MainViewModel.java:252)
> 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1378)
> 	at bisq.core.app.BisqSetup.step5(BisqSetup.java:331)
> 	at bisq.core.app.BisqSetup.lambda$startP2pNetworkAndWallet$9(BisqSetup.java:547)
> 	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
> 	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
> 	at javafx.beans.binding.ObjectBinding.invalidate(ObjectBinding.java:170)
> 	at com.sun.javafx.binding.BindingHelperObserver.invalidated(BindingHelperObserver.java:52)
> 	at com.sun.javafx.binding.ExpressionHelper$SingleInvalidation.fireValueChangedEvent(ExpressionHelper.java:136)
> 	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
> 	at javafx.beans.property.BooleanPropertyBase.fireValueChangedEvent(BooleanPropertyBase.java:104)
> 	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:111)
> 	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
> 	at bisq.core.app.P2PNetworkSetup$2.onDataReceived(P2PNetworkSetup.java:163)
> 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
> 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
> 	at bisq.network.p2p.P2PService.onDataReceived(P2PService.java:359)
> 	at bisq.network.p2p.peers.getdata.RequestDataManager$2.onComplete(RequestDataManager.java:339)
> 	at bisq.network.p2p.peers.getdata.RequestDataHandler.onMessage(RequestDataHandler.java:282)
> 	at bisq.network.p2p.network.NetworkNode.lambda$onMessage$4(NetworkNode.java:357)
> 	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
> 	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
> 	at bisq.network.p2p.network.NetworkNode.onMessage(Netwo [...]

2019-11-01 09:21 UTC, freimair commented
btw. how is this PR related to https://github.com/bisq-network/bisq/pull/3316?

2019-11-01 14:03 UTC, niyid commented
> btw. how is this PR related to #3316?

Implementing sort order for table views with none. This applied to about 4 such table views.

2019-11-07 17:59 UTC, niyid commented
@freimair 
This issue is resolved.

2019-11-09 14:36 UTC, freimair commented
no it is not. just checked again. please test your contributions better. or else we are forced to ignore your contributions (as they suck up way too much of our resources).

have you pushed your changes?

2019-11-09 16:30 UTC, niyid commented
> no it is not. just checked again. please test your contributions better. or else we are forced to ignore your contributions (as they suck up way too much of our resources).
> 
> have you pushed your changes?

Apologies about that. I will check and fix.

2019-11-09 17:08 UTC, niyid commented
This is the last commit 8 days ago:

https://github.com/bisq-network/bisq/commit/0cd9b5048be4d4407b72fd19396982718af53c92

![Screenshot from 2019-11-09 18-05-06](https://user-images.githubusercontent.com/20237127/68532298-df164380-031b-11ea-86b7-e5752a6b07b2.png)

2019-11-12 13:29 UTC, ripcurlx requested changes
NACK - Did you test this changes once? Obviously not, as nothing worked as expected. Having PRs like this as a reviewer makes it quite frustrating as it consumes more time reviewing it than implementing it myself.

2019-11-12 13:29 UTC, ripcurlx commented on desktop/src/main/java/bisq/desktop/main/market/offerbook/OfferBookChartView.java
> +
The list in the offer book chart view is just a teaser and the the volume column is set to sortable false which will make this code not working. So just revert the changes at this place.

2019-11-12 13:29 UTC, ripcurlx commented on desktop/src/main/java/bisq/desktop/main/dao/bonding/roles/RolesView.java
> +        tableView.getSortOrder().add(column);
Why are you sorting this based on lockup date if the name is displayed without any date information displayed. This just makes it confusing for the user.

2019-11-12 13:29 UTC, ripcurlx commented on desktop/src/main/java/bisq/desktop/main/dao/bonding/reputation/MyReputationView.java
> +        tableView.getSortOrder().add(column);
Again pointless defining a string to be sorted for as it is the default behavior.

2019-11-12 13:29 UTC, ripcurlx commented on desktop/src/main/java/bisq/desktop/main/dao/bonding/bonds/BondsView.java
> +        tableView.getSortOrder().add(column);
Don't change the default sort order to amount. Atm it is sorted by lockup date and it should stay like that. And all this doesn't work at all as desired as you have applied sorting to a string value which is the default behavior.

2019-11-12 13:29 UTC, ripcurlx commented on desktop/src/main/java/bisq/desktop/main/overlays/windows/ProposalResultsWindow.java
>          votesTableView.getColumns().add(column);
This has no effect as the columns are not sortable right now.

2019-11-12 15:06 UTC, closed without merging