Show only active roles in "Bonded Roles" table
bisq-network/bisq pull request #3320
Opened 2019-09-24 13:02 UTC by ben-kaufman

Fix #3271.
Filter the bonded roles list to contain only active bonds in the RolesView table.

2019-09-24 22:51 UTC, chimp1984 approved these changes
utACK

2019-09-25 13:52 UTC, wiz commented
I don’t think this is the correct fix, because the table needs to show inactive bonds that have been approved but not yet posted.

2019-09-25 16:58 UTC, sqrrm requested changes
NACK

As @wiz says, this will filter out all non committed bonds. What needs to be done is to filter out failed proposals to take on a bonded role but still show those role proposals that have been accepted by the DAO but not yet locked up their funds in a bond.

2019-09-25 18:59 UTC, chimp1984 commented
>I don’t think this is the correct fix, because the table needs to show inactive bonds that have been approved but not yet posted.

Yes you are right! Sorry for the too quick utACK!  Good to have more eyes on that!   

NACK

2019-11-12 13:32 UTC, ripcurlx commented
@ben-kaufman Are you up for making the required changes? See comments above ^^

2019-11-23 09:33 UTC, wiz commented
@ripcurlx I looked into this at the time the issue was created, but I didn't try to fix it because I thought it would be too dangerous to make the necessary changes to DAO code to filter the data as needed.. which I guess is why the bug exists in the first place. I suggest to close as WONTFIX unless you or chimp wants to fix it.

2019-11-24 18:11 UTC, chimp1984 commented
Replaced by https://github.com/bisq-network/bisq/pull/3676

This PR can be closed.

2019-11-26 08:51 UTC, closed without merging