Show BSQ trade fee in % per day
bisq-network/bisq pull request #3357
Opened 2019-10-03 07:32 UTC by niyid

Solution to issue #3292

2019-11-01 11:33 UTC, freimair commented
just a note for the future: would you please use the official keywords for closing issues https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords? Thanks!

2019-11-01 14:45 UTC, niyid commented
> just a note for the future: would you please use the official keywords for closing issues https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords? Thanks!

Noted with thanks.

2019-11-09 10:39 UTC, freimair requested changes
looks good. except for the formatting issues. Please resolve them and then we can get this PR merged.

2019-11-09 10:39 UTC, freimair commented on desktop/src/main/java/bisq/desktop/main/market/trades/TradesChartsView.java
> +	private void createCharts() {
formatting seems off

```suggestion
    private void createCharts() {
```

2019-11-09 10:39 UTC, freimair commented on desktop/src/main/java/bisq/desktop/main/market/trades/TradesChartsView.java
> +        //TODO bisqBurnSeries should only be added when model.getCurrencyCode() == "BSQ" ???
imo no, every time, since BSQ can be used to fund all transaction fees

@chimp1984 ?

2019-11-09 10:39 UTC, freimair commented on desktop/src/main/java/bisq/desktop/main/market/trades/TradesChartsViewModel.java
> +
formatting seems off. We use space-only indentation.

2019-11-11 10:31 UTC, niyid commented
@freimair 

Curious why the PR is not automatically merged as advised here:

> **### Merging is blocked**
> Merging can be performed automatically once the requested changes are addressed.

2019-11-11 10:33 UTC, ripcurlx commented
> @freimair
> 
> Curious why the PR is not automatically merged as advised here:
> 
> > ###**Merging is blocked**
> > Merging can be performed automatically once the requested changes are addressed.

The reviewer has to accept the requested changes, otherwise anything could be added and automatically merged to master without an additional review.

2019-11-11 10:35 UTC, niyid commented
> > @freimair
> > Curious why the PR is not automatically merged as advised here:
> > > ###**Merging is blocked**
> > > Merging can be performed automatically once the requested changes are addressed.
> 
> The reviewer has to accept the requested changes, otherwise anything could be added and automatically merged to master without an additional review.

Ah. I see. Thanks for the clarification. I thought maybe the message means the reviewer had put in some condition to check for merge automation.

2019-11-11 13:30 UTC, freimair approved these changes
Ack

2019-11-12 14:07 UTC, ripcurlx commented
@niyid This PR contains unsigned commits.

2019-11-12 14:20 UTC, ripcurlx requested changes
NACK - Based on my comment here: https://github.com/bisq-network/bisq/issues/3292#issuecomment-552913146

2019-12-19 16:06 UTC, closed without merging