List ZBit (ZBT)
bisq-network/bisq pull request #3560
Opened 2019-11-05 05:54 UTC by MidoriDaria

- Official project URL: https://zbitofficial.io/
- Official block explorer URL: http://explorer.zbitofficial.io/

2019-11-05 08:17 UTC, blabno requested changes
NACK per comments

2019-11-05 08:17 UTC, blabno commented on assets/src/main/java/bisq/asset/coins/ZBit.java
> +@AltCoinAccountDisclaimer("account.altcoin.popup.ZBT.msg")
Missing English translation of this message.

2019-11-19 16:38 UTC, blabno approved these changes
ACK

2019-11-21 08:34 UTC, ripcurlx submitted a review, later dismissed
utACK - based on https://github.com/bisq-network/bisq/pull/3560#pullrequestreview-319183359

2019-11-21 08:35 UTC, ripcurlx commented
@MidoriDaria You need to sign your commit https://help.github.com/articles/signing-commits-using-gpg before I'm able to merge it.

2019-11-21 08:36 UTC, ripcurlx requested changes
NACK - because of https://github.com/bisq-network/bisq/pull/3560#issuecomment-556977035

2019-12-28 09:11 UTC, closed without merging