Account validation
bisq-network/bisq pull request #3575
Opened 2019-11-07 12:18 UTC by beingindot

https://github.com/bisq-network/bisq/issues/3460

Added empty check validation for 
popmoney/uphold/revolut/zelle

bank forms already have required changes with previous PR.

2019-11-12 03:56 UTC, chimp1984 submitted a review, later dismissed
utACK

2019-11-13 16:45 UTC, ripcurlx requested changes
NACK - Please see my comments

2019-11-13 16:45 UTC, ripcurlx commented on desktop/src/main/java/bisq/desktop/components/paymentmethods/ClearXchangeForm.java
> +        setAccountNameWithString(mobileNrInputTextField.getText().trim());
That is not necessary anymore as your other PR got merged already.

2019-11-13 16:45 UTC, ripcurlx commented on desktop/src/main/java/bisq/desktop/components/paymentmethods/MoneyBeamForm.java
> +        setAccountNameWithString(accountIdInputTextField.getText().trim());
That is not necessary anymore as your other PR got merged already.

2019-11-13 16:45 UTC, ripcurlx commented on desktop/src/main/java/bisq/desktop/components/paymentmethods/PopmoneyForm.java
> +        setAccountNameWithString(accountIdInputTextField.getText().trim());
That is not necessary anymore as your other PR got merged already.

2019-11-13 16:45 UTC, ripcurlx commented on desktop/src/main/java/bisq/desktop/components/paymentmethods/RevolutForm.java
> +        setAccountNameWithString(accountIdInputTextField.getText().trim());
That is not necessary anymore as your other PR got merged already.

2019-11-13 16:45 UTC, ripcurlx commented on desktop/src/main/java/bisq/desktop/components/paymentmethods/UpholdForm.java
> +        setAccountNameWithString(accountIdInputTextField.getText().trim());
That is not necessary anymore as your other PR got merged already.

2019-11-13 16:46 UTC, ripcurlx commented
@beingindot Also all your commits need signing and you need to resolve the conflict now that your other PR got merged.

2019-11-14 07:10 UTC, beingindot commented
@ripcurlx Resolved conflicts and included changes. pls check.

2019-11-14 13:49 UTC, ripcurlx approved these changes

2019-11-14 13:49 UTC, merged