Add colon after paymentMethod on tooltip
bisq-network/bisq pull request #3619
Opened 2019-11-16 15:07 UTC by rafaelpac

This is a silly fix of the tooltip. Every item on the tooltip have colons, some added with getWithCol and some hardcoded on the string. This one doesn't have.

2019-11-16 21:21 UTC, rafaelpac commented
Sorry, I made a little confusion...
My first change was a silly change to add a colon missing in a tooltip.
This was my first ever pull request, I am a total noob with github.
Later, I think I found the bug that causes issue #3601 
The bug only happens when the offer has min-max value range.
The new `isAmountValidForOffer` in `PaymentAccountUtil.java` consider only the max amount, but the button to take the offer is ungrayed considering the min amount, which causes the bug.
Both fixes came together here, I don't really know how should I have done it to make them separate.

2019-11-17 02:33 UTC, chimp1984 commented
@rafaelpac 
The second commit needs to be removed from that PR as it is a completely different issue.
You can close the PR and make a new one with the colon fix. The second one requires @ripcurlx or @sqrrm to verify.

2019-11-17 02:33 UTC, chimp1984 requested changes
NACK
The 2nd commit needs to be in a separate PR

2019-11-17 03:11 UTC, rafaelpac commented
Yes, I'm sorry... I know there should be two separate pull requests, but I can't find out how to do it. I need separate branches in my fork, is it? I am afraid of clicking more and make it worse...

2019-11-17 21:37 UTC, rafaelpac commented
Ok, I will close this and open two separate ones. I think I know how to do it now.

2019-11-17 21:37 UTC, closed without merging