[BUGFIX] #3629 (Duplicate payloads w/ 20-byte and 32-byte keys)
bisq-network/bisq pull request #3636
Opened 2019-11-19 21:06 UTC by julianknutsen

New commits start at 849155a

fixes #3629

Hotfix Needed: No

There was a bug when reconstructing the in-memory HashMap for `ProtectedStoragePayload` objects implementing the `PersistablePayload` object. This had two related bugs:

1) The in-memory map would end up with duplicate Payloads if a node rebuilt a ProtectedStorageEntry from the 20-byte key, then received the 32-byte key from the seednode during initialization or from an update on the P2P network.

2) An initializing node would resync known payloads from the seednode since the `Payload` existed with both the 20-byte and 32-byte key.

This PR cleans up the usages so that all outward users see the 32-byte key and all internal users can use the existing 20-byte key for persistence. This design is much safer than transitioning all persistent users to 32-byte keys and writing on-disk upgrade code.

All external listeners of Payloads don't look at the key. So, although they will receive 2 onAdded() calls instead of 1, they do the right thing by excluding the second payload since it is identical. I don't think there is any reason to publish a hotfix for this.

## Upgrade behavior
**New Seednode <--> Old Client**
The seednode will only have 1 32-byte key for each unique payload, but the client node may still have a 20-byte key that it will send as a known key. The seednode will ignore this known key, send back the 32-byte key `Payload` and the client node will update its map with the 32-byte key. This mimics existing behavior.

**Old Seednode <--> New Client**
The seednode will have 1 20-byte key and 1 32-byte key for the same unique payload. The client will only have the 32-byte key and will send it is a known key. The seednode will transmit the 20-byte payload back to the client who will ignore it.

**New Seednode <--> New Client**
Both the seednode and the client will only have 1 32-byte key for each unique payload. The client will include its 32-byte key as a known key which will match the key in the seednode map. No duplicate `Payload` objects will be transmitted.

2019-11-20 10:24 UTC, freimair requested changes
I might be missing something here so here are some control questions to foster my understanding:

> ## Upgrade behavior
> **New Seednode <--> Old Client**
> The seednode will only have 1 32-byte key for each unique payload, but the client node may still have a 20-byte key that it will send as a known key. The seednode will ignore this known key, send back the 32-byte key `Payload` and the client node will update its map with the 32-byte key. This mimics existing behavior.

- So in the real world the old client will send roughly 2MB of 20-byte known keys to the new seed node.
- The new seed node ignores all of them and respond with _all_ data (close to our single-message size limit of 10MB)? (since it only received 20-byte keys and no 32-byte key)
- Does the old client memorize the 32-byte keys? after restart?
 
> **Old Seednode <--> New Client**
> The seednode will have 1 20-byte key and 1 32-byte key for the same unique payload. The client will only have the 32-byte key and will send it is a known key. The seednode will transmit the 20-byte `Payload` back to the client who will ignore it.

- why does the old seednode have 32-byte keys?
- the client sends only 32-byte keys for its known payloads, so the seed node will send _all_ 20-byte addressed payloads to the client (roughly 10MB of data) to every client.
- every time a client connects. Because new clients will not memorize the 20-byte keys?

2019-11-20 17:03 UTC, julianknutsen commented
> I might be missing something here so here are some control questions to foster my understanding:
> 
> > ## Upgrade behavior
> > **New Seednode <--> Old Client**
> > The seednode will only have 1 32-byte key for each unique payload, but the client node may still have a 20-byte key that it will send as a known key. The seednode will ignore this known key, send back the 32-byte key `Payload` and the client node will update its map with the 32-byte key. This mimics existing behavior.

**_This behavior is only for `ProtectedStoragePayload` objects implementing `PersistablePayload`. For now, this is just `TempProposalPayload`._**

> 
> * So in the real world the old client will send roughly 2MB of 20-byte known keys to the new seed node.

**_No, the client sends roughly 1kb of unnecessary 20-byte keys at startup for the `TempProposalPayload` objects._**

> * The new seed node ignores all of them and respond with _all_ data (close to our single-message size limit of 10MB)? (since it only received 20-byte keys and no 32-byte key)

**_No, the seednode sends back around 50kb of duplicate `TempProposal` data in `GetDataResponse`._**

> * Does the old client memorize the 32-byte keys? after restart?

**_No, old clients use the 20-byte key for persistence. So after restart all `TempProposalPayload` objects
are reconstructed with 20-byte keys. It only "works" because the seed nodes send 32-byte keys at
startup that the client nodes use to update their internal map._**

> 
> > **Old Seednode <--> New Client**
> > The seednode will have 1 20-byte key and 1 32-byte key for the same unique payload. The client will only have the 32-byte key and will send it is a known key. The seednode will transmit the 20-byte `Payload` back to the client who will ignore it.
> 
> * why does the old seednode have 32-byte keys?

**_During initial creation of `TempProposalPayload` and during `MyProposalListService::rePublishMyProposalsOnceWellConnected()` send them to the network. If these are "new", the seednode will save it as a 20-byte key in the `ProtectedDataStoreService`, but also keep it in-memory with the 32-bye key like the other `ProtectedStoragePayloads`. This allows it to give the 32-byte keys to new nodes on startup._**

> * the client sends only 32-byte keys for its known payloads, so the seed node will send _all_ 20-byte addressed payloads to the client (roughly 10MB of data) to every client.
> * every time a client connects. Because new clients will not memorize the 20-byte keys?

**_It isn't that the new clients won't memorize it, it is that they only have in-memory representations using 32-byte keys now. So, until the seednode is updated to ONLY have 32-byte keys and NOT have 20-byte keys in the internal map, the seednodes will still send back the 20-byte key payloads. It isn't harmful because the duplicate paylaods sent back are ignored from the new client._**

2019-11-21 00:52 UTC, julianknutsen commented
After a deeper investigation of the persistence code, I found that TempProposals are stored to disk as a List<ProtectedStorageEntry> and the Map.Entry<ByteArray, ProtectedStorageEntry> is actually reconstructed in-memory. So, I've updated e212240 accordingly with a much cleaner patch that just changes the 20-byte key to a 32-byte key.

2019-11-21 10:23 UTC, ripcurlx commented
@freimair Can you please review the changes and ACK if ok?

2019-11-21 10:23 UTC, ripcurlx approved these changes
utACK

2019-11-21 19:54 UTC, freimair approved these changes
Ack.

Now is the time to do the change, as only `TempProposalPayload` and the deprecated `TradeStatistics` are affected by the change. But it will generate additional network load if we are not quick in updating the seednodes.

2019-11-21 20:15 UTC, julianknutsen commented
I updated the bug as well but wanted to include it here.

After more investigation, 455f7d2 also fixes an additional issue where we were retransmitting every non-persistable `ProtectedStorageEntry` in the `GetUpdatedDataRequest` path.  By using the in-memory map instead of the protectedDataStore, we now stop transmitting duplicates. Here was the breakdown of the duplicate transmissions before that patch:

```
#################################################################
Received 724 instances
RefundAgent: 1 (915 B)
Filter: 2 (5.7 KB)
TempProposalPayload: 56 (33.9 KB)
MailboxStoragePayload: 457 (2.0 MB)
Alert: 1 (826 B)
Mediator: 2 (1.8 KB)
OfferPayload: 205 (249.6 KB)
################################################################# 
```

2019-11-26 13:34 UTC, merged