Account number label in Swedish fix
bisq-network/bisq pull request #3645
Opened 2019-11-20 19:12 UTC by rafaelpac

Fixes #3641
According to this issue, the label "Bankgiro number", as it was hardcoded in BankUtil.java, should not be used in Sweden.
The label "Kontonummer" is the correct one to be used in Sweden and Norway.

Account number validation is implemented to Norwegian accounts in AccountNrValidator.java.
There is no validation implemented to Swedish accounts, so nothing to change there.
If account validation for Sweden is needed, a different method would be needed (see Wikipedia reference below):

![image](https://user-images.githubusercontent.com/6444444/69269777-8151e900-0bb0-11ea-9f9b-80e0212a873c.png)

2019-11-20 19:15 UTC, Bisq2People commented
Swedish account validation checks that the account number consists of:

11 or 13 or 15 decimal digits.

2019-11-21 08:56 UTC, ripcurlx commented
@rafaelpac Could you please resolve the conflict with BankUtil and update your commit messages to follow https://chris.beams.io/posts/git-commit/#7-rules - we know that you updated BankUtil.java 😉 . Thanks!

2019-11-21 08:56 UTC, ripcurlx requested changes
NACK - https://github.com/bisq-network/bisq/pull/3645#issuecomment-556984208

2019-11-21 08:57 UTC, ripcurlx commented
And please squash it into one commit in that case.

2019-11-21 20:20 UTC, camahama commented
Hoping this is the correct way and place to post this bug. When I try to register a new SEPA account (Swedish Skandiabanken), the SAVE NEW ACCOUNT button remains grey and unclickable. No error messages. The same account has worked previously. Running Bisq v. 1.2.3.

2019-11-21 20:28 UTC, Bisq2People commented
@camahama
This is not the right place but it looks like a bug, because when you toggle SEK/EURO drop-down menu the grey out disappears.

2019-11-27 19:35 UTC, rafaelpac commented
I'm sorry... I can't find how to change the commit message.

2019-12-06 13:09 UTC, ripcurlx commented
> I'm sorry... I can't find how to change the commit message. I think it is not doable in the web interface, right?

You have to change your commit history locally and force push your changes to your remote PR branch.
See https://www.internalpointers.com/post/squash-commits-into-one-git for reference how to do it.

2020-01-02 18:19 UTC, ripcurlx commented on core/src/main/java/bisq/core/locale/BankUtil.java
> +                return "Kontonummer"; // do not translate as it is used in norwegian and swedish only
As it looks like the label is exactly the same I think we could merge those two cases.

2020-01-02 18:20 UTC, ripcurlx commented
> I'm sorry... I can't find how to change the commit message. I think it is not doable in the web interface, right?

@rafaelpac Besides my comment on the cases here is how you squash multiple commits into one locally: https://www.internalpointers.com/post/squash-commits-into-one-git

2020-01-02 20:18 UTC, rafaelpac commented
I'm sorry, I completely forgot about this PR.
This was a quick fix I did for somebody's issue about a label in Swedish, I was studying this file at that time, so it was easy for me to do it.
I don't use git locally, I only use the github web interface (only for very small fixes and to study the code, I am not a developer).
So I can't easily fix the mess I did here. It is easier for now to just close this and open a new clean one.
I will try that, I hope I don't mess it up again.

2020-01-02 20:18 UTC, closed without merging