Add zh_TW translations (Chinese Traditional)
bisq-network/bisq pull request #3714
Opened 2019-11-28 23:17 UTC by wiz

2019-12-02 09:44 UTC, ripcurlx requested changes
NACK - @wiz Thanks for the changes. I don't remember anymore if there was a reason not to support country specific language files, but I don't see a reason why not to do it. Please see my comment regarding one missing change.

2019-12-02 09:44 UTC, ripcurlx commented on core/update_translations.sh
> +mv "$translations/zh_TW.properties" "$i18n/displayStrings_zh-hant.properties"
To support that you need to update also `tx pull -l de,el_GR,es,ja,pt,ru,zh_CN,vi,th_TH,fa,fr,pt_BR` to `tx pull -l de,el_GR,es,ja,pt,ru,zh_CN,zh_TW,vi,th_TH,fa,fr,pt_BR`

2019-12-02 11:34 UTC, ripcurlx commented
@arunasurya @wiz We do have Chinese simplified already as a supported core language, but not traditional Chinese. How do we want to handle the adding of country variants of an existing language? I think it would be good to have something official (proposal or similar) to state the reasoning for adding this new language variant (as it also immediately makes eligible for compensation)

2019-12-02 20:31 UTC, arunasurya commented
@ripcurlx , I agree with you that it is good to have clear reasoning for adding a new language. Right now, we don't have a clear policy but rather rough guidelines. Perhaps it is a good idea to have a more explicit policy. Meanwhile, I am communicating with the two translators who have done (ff98sha and wdljt) to figure out how important traditional Chinese is for Bisq, etc.

2019-12-03 06:00 UTC, cryptosnip commented
1.4 Billion people speak & write Mandarin - 1/3 the worlds population. So what is the the problem??Traditional Chinese is mostly written and is used in academic and traditional medicine and arts/music...

-- 
 Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
 https://tutanota.com


Dec 3, 2019, 03:31 by notifications@github.com:

>
> @ripcurlx <https://github.com/ripcurlx>>  , I agree with you that it is good to have clear reasoning for adding a new language. Right now, we don't have a clear policy but rather rough guidelines. Perhaps it is a good idea to have a more explicit policy. Meanwhile, I am communicating with the two translators who have done (ff98sha and wdljt) to figure out how important traditional Chinese is for Bisq, etc.
>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, > view it on GitHub <https://github.com/bisq-network/bisq/pull/3714?email_source=notifications&email_token=AH5DVYBEICBOPFXN742USADQWVWCVA5CNFSM4JSZJJ5KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFUZOJA#issuecomment-560568100>> , or > unsubscribe <https://github.com/notifications/unsubscribe-auth/AH5DVYAPYIPOTFNXHNPZY5TQWVWCVANCNFSM4JSZJJ5A>> .
>

2019-12-03 09:45 UTC, ripcurlx commented
> 1.4 Billion people speak & write Mandarin - 1/3 the worlds population. So what is the the problem??

There is no problem with it, we just should have a transparent workflow when a new language or language variant is added as we only support a couple of core languages right now which are also up for compensation. Just to change it within a PR might go through unnoticed and might cause irritation by others who want to get their language added to Bisq as well.

2019-12-03 10:10 UTC, ripcurlx commented
> @ripcurlx , I agree with you that it is good to have clear reasoning for adding a new language. Right now, we don't have a clear policy but rather rough guidelines. Perhaps it is a good idea to have a more explicit policy. Meanwhile, I am communicating with the two translators who have done (ff98sha and wdljt) to figure out how important traditional Chinese is for Bisq, etc.

I think it is important, but it was only communicated through personal chat with me from @wiz. So I'm up for adding it in this case as it is just a language variant and it would add native language support for people based in Hongkong.

2019-12-03 10:26 UTC, ripcurlx submitted a review, later dismissed

2019-12-03 10:54 UTC, ripcurlx approved these changes
ACK

Tested it locally on Regtest and also tried to update translations from Transifex. Everything works as expected.

2019-12-03 11:00 UTC, merged

2019-12-05 00:56 UTC, arunasurya commented
I think that the translators should have made a proposal to add a new language before it was merged. I was looking into it and tried to evaluate if it should be  a core language. I don't think there was a consensus on adding traditional Chinese from all sides...Is it now officially a core language?