Add and rename Portfolio History columns meaningfully.
bisq-network/bisq pull request #3785
Opened 2019-12-13 00:11 UTC by niyid

Fixes #3338.

Fixes #replaceWithIssueNr, fixes #replaceWithIssueNr

Your PR description here.

2020-01-13 14:54 UTC, ripcurlx requested changes
NACK - Because of code format issues. Please also rebase your PR against master so it is easier also to test with a mainnet client. Thanks!

2020-01-13 14:54 UTC, ripcurlx commented on desktop/src/main/java/bisq/desktop/main/portfolio/closedtrades/ClosedTradesView.java
> +
Nearly every line in this file except the imports has issues with using the wrong spacing (not using our format style)

2020-01-13 14:54 UTC, ripcurlx commented on desktop/src/main/java/bisq/desktop/main/portfolio/closedtrades/ClosedTradesViewModel.java
> +import bisq.common.crypto.KeyRing;
Empty line is missing before and after this import to be in line with our imports format

2020-01-13 14:54 UTC, ripcurlx commented on desktop/src/main/java/bisq/desktop/main/portfolio/closedtrades/ClosedTradesViewModel.java
> +
Unnecessary spaces

2020-01-13 14:54 UTC, ripcurlx commented on desktop/src/main/java/bisq/desktop/main/portfolio/closedtrades/ClosedTradesViewModel.java
> +
Format issues as well. Please apply our code format style.

2020-01-17 11:22 UTC, ripcurlx commented
@niyid I activated yesterday codacy's PR Quality Review for the Bisq repository. It found for your PR a couple of issues which you can view in the Details link next to the PR check. Please review and push fixes for this issues to trigger a re-review by codacy. Thanks!

2020-02-08 22:54 UTC, niyid commented
@ripcurlx 
A "waiting for author" label was added 26 days ago. I am not sure it was intended to be active on this PR for that long.

2020-02-26 11:28 UTC, ripcurlx requested changes
NACK

Please see my comments and also please rebase against master to make it easier to review. Thanks!

2020-02-26 11:28 UTC, ripcurlx commented on desktop/src/main/java/bisq/desktop/main/portfolio/closedtrades/ClosedTradesView.java
> +        });
This can be done within one line
```
makerMiningFeeColumn.setComparator(Comparator.comparing(model::getMakerMiningFee));
```

2020-02-26 11:28 UTC, ripcurlx commented on desktop/src/main/java/bisq/desktop/main/portfolio/closedtrades/ClosedTradesView.java
> +        });
This can be done within one line
```
takerMiningFeeColumn.setComparator(Comparator.comparing(model::getTakerMiningFee));
```

2020-02-26 11:28 UTC, ripcurlx commented on desktop/src/main/java/bisq/desktop/main/portfolio/closedtrades/ClosedTradesView.java
> +        });
This can be done within one line
```
makerTradingFeeColumn.setComparator(Comparator.comparing(model::getMakerTradingFee));
```

2020-02-26 11:28 UTC, ripcurlx commented on desktop/src/main/java/bisq/desktop/main/portfolio/closedtrades/ClosedTradesView.java
> +        });
This can be done within one line
```
takerTradingFeeColumn.setComparator(Comparator.comparing(model::getTakerTradingFee));
```

2020-02-26 11:28 UTC, ripcurlx commented on desktop/src/main/java/bisq/desktop/main/portfolio/closedtrades/ClosedTradesViewModel.java
> +
This method is never used.

2020-02-26 11:28 UTC, ripcurlx commented on desktop/src/main/java/bisq/desktop/main/portfolio/closedtrades/ClosedTradesViewModel.java
> +        this.keyRing = keyRing;
Is never used

2020-02-27 01:43 UTC, niyid commented
@ripcurlx All issues resolved. Please remember to remove "waiting for author" label.

2020-04-04 07:02 UTC, closed without merging