Add user preference combobox for BSQ block explorer with random default
bisq-network/bisq pull request #3792
Opened 2019-12-15 15:20 UTC by wiz

Implements https://github.com/bisq-network/proposals/issues/143

Needs review and testing

2019-12-15 16:01 UTC, chimp1984 submitted a review, later dismissed
utACK

IMO betanet and testnet can be removed...

2019-12-15 16:01 UTC, chimp1984 commented on core/src/main/java/bisq/core/user/Preferences.java
> +    private static final ArrayList<BlockChainExplorer> BSQ_BETA_NET_EXPLORERS = new ArrayList<>(Collections.singletonList(
Do we still run betanet exploreres? I think its not worth the effort if so.

2019-12-15 16:01 UTC, chimp1984 commented on core/src/main/java/bisq/core/user/Preferences.java
> +            new BlockChainExplorer("BSQ", "http://explorer.testnet.bisq.network/tx.html?tx=", "http://explorer.testnet.bisq.network/Address.html?addr=")
Same with testnet. I doubt there is a testnet explorer running and testnet is pretty un-usable anyway for app testing.

2019-12-17 10:12 UTC, ripcurlx requested changes
NACK - please see the comments from @chimp1984 and myself.

2019-12-17 10:12 UTC, ripcurlx commented on core/src/main/java/bisq/core/user/Preferences.java
> +    private static final ArrayList<BlockChainExplorer> BSQ_BETA_NET_EXPLORERS = new ArrayList<>(Collections.singletonList(
Yes, they are both not reachable ATM. I think we can remove them from here.

2019-12-17 16:42 UTC, sqrrm commented on core/src/main/java/bisq/core/user/Preferences.java
> +    private static final ArrayList<BlockChainExplorer> BSQ_BETA_NET_EXPLORERS = new ArrayList<>(Collections.singletonList(
I haven't run any betanet explorers for almost a year. Doubt anyone else has either.

2019-12-17 17:32 UTC, sqrrm submitted a review, later dismissed
utACK

2019-12-18 07:55 UTC, ripcurlx approved these changes
ACK

Tested it on Mainnet and everything works as expected for @wiz explorer. @sqrrm explorer should be available for our v1.2.5 release

2019-12-18 07:55 UTC, merged