Refactoring of and function in ValidationResult class
bisq-network/bisq pull request #3838
Opened 2019-12-28 20:47 UTC by beingindot

This function didnt have terminating short circuit 
which is important for and operator functions.

Also this function gets called multiple times since it's validation function. 
hence improving needed here.

After verifying usages, left out following two classes
1. PercentageNumberValidator - since it's using only two validation
2. PhoneNumberValidator - have variable inputs and this is only place.

2020-01-03 10:33 UTC, ripcurlx commented
@beingindot Could you please resolve the conflict? Thanks!

2020-01-16 14:36 UTC, ripcurlx requested changes
NACK - Please see my comment

2020-01-16 14:36 UTC, ripcurlx commented on core/src/main/java/bisq/core/util/validation/InputValidator.java
> +import java.util.Arrays;
Import statement is not used

2020-01-17 11:21 UTC, ripcurlx commented
@beingindot I activated yesterday codacy's PR Quality Review for the Bisq repository. It found for your PR a couple of issues which you can view in the Details link next to the PR check. Please review and push fixes for this issues to trigger a re-review by codacy. Thanks!

2020-01-20 06:57 UTC, beingindot commented
@ripcurlx Have removed unused and its passing now. pls review.

2020-01-29 10:11 UTC, ripcurlx commented
@beingindot Please make sure that you are applying our format style properly (see my commit https://github.com/bisq-network/bisq/pull/3838/commits/a9bbbdf54566afd623e77ecf348af65e036f16b7). I pushed it this time to save more review time on this, but will reject it in the next PR.

2020-01-29 10:26 UTC, ripcurlx approved these changes
ACK

I tested it on Regtest creating compensation request (BSQ Validator) an offer (all other validators)  and everything works as before.
Still I would appreciate for performance improvements in the future at least comparisons as in https://github.com/bisq-network/bisq/pull/3921#issue-367754081 so we make decisions based on data.

2020-01-29 10:27 UTC, merged