Redact DepositTxId when publishing TradeStatistics for user privacy
bisq-network/bisq pull request #3891
Opened 2020-01-11 23:45 UTC by wiz

Before:
```
  { 
    "currency": "JPY",
    "direction": "SELL",
    "tradePrice": 8791986900,
    "tradeAmount": 10000,
    "tradeDate": 1578784489588,
    "paymentMethod": "F2F",
    "offerDate": 1578784398352,
    "useMarketBasedPrice": true,
    "marketPriceMargin": 0.0,
    "offerAmount": 10000,
    "offerMinAmount": 10000,
    "offerId": "12635-224f7143-3366-46e7-9e14-7fa6f39fcb2b-125",
    "depositTxId": "9c67453e57cfc80e2c121caf54f8f739cef6c5d7e9afdceec7843436a920f9d8",
    "currencyPair": "BTC/JPY",
    "primaryMarketDirection": "SELL",
    "primaryMarketTradePrice": 87919869000000,
    "primaryMarketTradeAmount": 10000,
    "primaryMarketTradeVolume": 8791980000
  },
```

After:
```
  {
    "currency": "JPY", 
    "direction": "SELL",
    "tradePrice": 8791986900,
    "tradeAmount": 10000, 
    "tradeDate": 1578784489149,
    "paymentMethod": "F2F", 
    "offerDate": 1578784398352,
    "useMarketBasedPrice": true,
    "marketPriceMargin": 0.0,
    "offerAmount": 10000, 
    "offerMinAmount": 10000, 
    "offerId": "12635-224f7143-3366-46e7-9e14-7fa6f39fcb2b-125",
    "depositTxId": "0000000000000000000000000000000000000000000000000000000000000000",
    "currencyPair": "BTC/JPY",
    "primaryMarketDirection": "SELL",
    "primaryMarketTradePrice": 87919869000000,
    "primaryMarketTradeAmount": 10000, 
    "primaryMarketTradeVolume": 8791980000
  },
```

2020-01-15 23:38 UTC, chimp1984 requested changes
NACK

This would cause duplicated trade statistics if one trader has old verison and one trader has new version as the tx id is used for the hash. We need to fade that in with an activation date so the risk that old users are part of the trade is much lower. Also it should be declared nullable, set to null instead of the "0" string and handled accordingly in the protobuf methods and a comment should be added about the reasoning.

2020-01-16 00:15 UTC, wiz commented
@chimp1984 ah yes, those are some very good points. would you prefer to make the fix? it sounds like you want to do it 😅

2020-01-16 14:09 UTC, chimp1984 commented
I will not have time and will step out of Bisq after that cycle.

2020-01-16 15:34 UTC, ripcurlx requested changes
NACK - https://github.com/bisq-network/bisq/pull/3891#pullrequestreview-343593923

2020-01-21 15:59 UTC, ripcurlx commented
Closing as superseded by https://github.com/bisq-network/bisq/pull/3911.

2020-01-21 15:59 UTC, closed without merging