Make prompt text readable in dark mode
bisq-network/bisq pull request #4092
Opened 2020-03-24 09:44 UTC by ripcurlx

As this annoys me for a long time when using dark mode I quickly fixed this issue.
No compensation necessary - just fixing this was satisfaction enough ;-)

2020-03-24 10:05 UTC, wiz approved these changes
Excellent! For some reason, I never noticed that dark text on dark background before. I've tested this change while using dark theme and didn't notice any side effects :+1:

2020-03-24 10:06 UTC, wiz commented
```
Mar 24, 2020 7:04:48 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Caught 'java.lang.ClassCastException: java.base/java.lang.String cannot be cast to javafx.graphics@10.0.1/javafx.scene.paint.Color' while converting value for '-fx-prompt-text-fill' from rule '*.text-field' in stylesheet jar:file:/Applications/Bisq.app/Contents/Java/Bisq-1.2.9.jar!/bisq/desktop/bisq.css
Mar 24, 2020 7:04:48 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Caught 'java.lang.ClassCastException: java.base/java.lang.String cannot be cast to javafx.graphics@10.0.1/javafx.scene.paint.Color' while converting value for '-fx-prompt-text-fill' from rule '*.text-field' in stylesheet jar:file:/Applications/Bisq.app/Contents/Java/Bisq-1.2.9.jar!/bisq/desktop/bisq.css
```

2020-03-24 10:06 UTC, wiz requested changes
Actually just noticed this
```
Mar 24, 2020 7:04:48 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Caught 'java.lang.ClassCastException: java.base/java.lang.String cannot be cast to javafx.graphics@10.0.1/javafx.scene.paint.Color' while converting value for '-fx-prompt-text-fill' from rule '*.text-field' in stylesheet jar:file:/Applications/Bisq.app/Contents/Java/Bisq-1.2.9.jar!/bisq/desktop/bisq.css
Mar 24, 2020 7:04:48 PM javafx.scene.CssStyleHelper calculateValue
WARNING: Caught 'java.lang.ClassCastException: java.base/java.lang.String cannot be cast to javafx.graphics@10.0.1/javafx.scene.paint.Color' while converting value for '-fx-prompt-text-fill' from rule '*.text-field' in stylesheet jar:file:/Applications/Bisq.app/Contents/Java/Bisq-1.2.9.jar!/bisq/desktop/bisq.css
```

2020-03-24 11:46 UTC, ripcurlx commented
> Actually just noticed this
> 
> ```
> Mar 24, 2020 7:04:48 PM javafx.scene.CssStyleHelper calculateValue
> WARNING: Caught 'java.lang.ClassCastException: java.base/java.lang.String cannot be cast to javafx.graphics@10.0.1/javafx.scene.paint.Color' while converting value for '-fx-prompt-text-fill' from rule '*.text-field' in stylesheet jar:file:/Applications/Bisq.app/Contents/Java/Bisq-1.2.9.jar!/bisq/desktop/bisq.css
> Mar 24, 2020 7:04:48 PM javafx.scene.CssStyleHelper calculateValue
> WARNING: Caught 'java.lang.ClassCastException: java.base/java.lang.String cannot be cast to javafx.graphics@10.0.1/javafx.scene.paint.Color' while converting value for '-fx-prompt-text-fill' from rule '*.text-field' in stylesheet jar:file:/Applications/Bisq.app/Contents/Java/Bisq-1.2.9.jar!/bisq/desktop/bisq.css
> ```

😬 good catch - I'll have a look why this is happening

2020-03-24 11:53 UTC, ripcurlx commented
I fixed a bug with another bug 😝 Just force-pushed the correct implementation.

2020-03-26 12:21 UTC, sqrrm approved these changes
utACK

2020-03-26 12:22 UTC, merged