OfferBook: Show min-max range for amount and volume
bisq-network/bisq pull request #4225
Opened 2020-05-02 12:42 UTC by cd2357

The OfferBook tables now show the amount and the volume as min-max range, where appropriate.

For the offers that have no range defined, the single values are shown.

Fixes #3129

2020-05-05 15:43 UTC, sqrrm requested changes
Could you provide a before and after screenshot for the UI changes? It will help a lot to do the review.

2020-05-06 20:24 UTC, cd2357 commented
Adding screenshots:

Before (buy and sell offers in the Offerbook did not show the min-max range) :

![Screenshot from 2020-05-06 22-22-25](https://user-images.githubusercontent.com/15956136/81224575-373ab380-8fe8-11ea-8d5b-905e99b684f9.png)

After (both buy and sell orders now show the min-max range, for volume and price) : 

![Screenshot from 2020-05-06 22-20-09](https://user-images.githubusercontent.com/15956136/81224638-4c174700-8fe8-11ea-9ed1-787337e4583d.png)

2020-05-10 09:17 UTC, petrhejna commented on desktop/src/main/java/bisq/desktop/main/market/offerbook/OfferBookChartView.java
> +                             * Should not be called for empty cells
Is this comment really needed? Maybe naming `renderCellContent()` is enough as it is private method in very specific context.

2020-05-10 09:19 UTC, petrhejna commented
ACK

2020-05-12 10:53 UTC, sqrrm approved these changes
utACK

2020-05-12 10:54 UTC, sqrrm commented
@petrhejna Thanks for reviewing. Did you read up on the usage of ACK, utACK and NACK? ACK meaning you have actually tested this PR.

2020-05-12 10:54 UTC, merged

2020-05-12 21:29 UTC, petrhejna commented
@sqrrm yes, I did test it