Secondary sort order for offer book
bisq-network/bisq pull request #4259
Opened 2020-05-15 17:22 UTC by dmos62

Supersedes https://github.com/bisq-network/bisq/pull/4168. This is a rewrite of that PR.

Adds a secondary sort order to offers in market offer book by offer amount that goes from high to low. Also, refactors-away overcomplicated previous implementation of primary sort.

Co-authored-by: Florian Reimair <office@florianreimair.at>
Co-authored-by: cd2357 <15956136+cd2357@users.noreply.github.com>

![offerbook-secondary-sort-refactor](https://user-images.githubusercontent.com/2715476/82078128-eb22f980-96e0-11ea-800b-af281a06899a.png)

2020-05-16 19:00 UTC, petrhejna commented
The class `OfferBookChartViewModel` has test-file `OfferBookChartViewModelTest` I believe the change should be reflected in the tests as well.

2020-05-16 23:58 UTC, ghost approved these changes
~~Tested, ACK.  Nice & clean.~~
[edit] There's a bug in altcoin markets - appears to sort the price incorrectly.

![image](https://user-images.githubusercontent.com/47253594/82768104-5d3ac300-9df2-11ea-854b-ebec563c2b18.png)

2020-05-25 00:46 UTC, ghost requested changes

2020-05-25 00:46 UTC, jmacxx commented on desktop/src/main/java/bisq/desktop/main/market/offerbook/OfferBookChartViewModel.java
> +
boolean isCrypto = CurrencyUtil.isCryptoCurrency(getCurrencyCode());

2020-05-25 00:46 UTC, jmacxx commented on desktop/src/main/java/bisq/desktop/main/market/offerbook/OfferBookChartViewModel.java
> +            offerPriceComparator.reversed() // Buy offers, as opposed to sell offers, are primarily sorted from high price to low.
(isCrypto ? offerPriceComparator : offerPriceComparator.reversed()) // Buy offers, as opposed to sell offers, are primarily sorted from high price to low.

2020-05-25 00:46 UTC, jmacxx commented on desktop/src/main/java/bisq/desktop/main/market/offerbook/OfferBookChartViewModel.java
> +            offerPriceComparator
(isCrypto ? offerPriceComparator.reversed() : offerPriceComparator)

2020-05-25 09:42 UTC, dmos62 commented
@jmacxx thanks again! Fixed the ordering. I hadn't noticed that the tables are switched in Altcoin markets. Included an in-code explanation.
![offer book bsq fixed altcoin sort](https://user-images.githubusercontent.com/2715476/82800848-a6375980-9e7c-11ea-8416-fa5fb2377b02.png)
![offerbook eur fixed altcoin sort](https://user-images.githubusercontent.com/2715476/82800878-b2231b80-9e7c-11ea-86fe-7c634cdaf18b.png)

2020-05-25 13:04 UTC, ghost approved these changes
:+1: Looks good in both fiat and altcoin markets now.

2020-05-25 14:04 UTC, sqrrm approved these changes
utACK

2020-05-25 14:04 UTC, sqrrm commented on desktop/src/main/java/bisq/desktop/main/market/offerbook/OfferBookChartViewModel.java
> +
Prefer no blank lines at the beginning of methods.

2020-05-25 14:04 UTC, merged