Optimize AssetService
bisq-network/bisq pull request #4409
Opened 2020-08-12 21:12 UTC by chimp1984

Previous version had several performance issues:
- We kept tradeStatistics in a lookup map in memory (about 40 MB)
- We built up the StatefulAssets even if it was not used/needed.
Building the StatefulAssets was an expensive call.
- AssetTradeActivityCheck was only used for printing out statistics and
called on startup causing performance cost.

Optimized version:
- We call build the StatefulAssets only on demand (user activates
view). Method call takes now 22 ms.
- We create a optimized lookup map with a tuple of the data we need
and keep it as local variable.
- We removed AssetTradeActivityCheck.

Thanks to the profiling reporting from:
https://github.com/bisq-network/proposals/issues/199

Fixes #replaceWithIssueNr, fixes #replaceWithIssueNr

Your PR description here.

2020-08-21 17:06 UTC, sqrrm requested changes
Looks good. Would prefer to have pure refactoring as separate commits for easier review.

Added a couple of suggestions before merging.

Needs review from @ManfredKarrer since it touches core/dao

2020-08-21 17:06 UTC, sqrrm commented on core/src/main/java/bisq/core/dao/governance/asset/AssetService.java
> +
```suggestion

    // Get the trade volume from lookupDate until current date
```

2020-08-21 17:06 UTC, sqrrm commented on desktop/src/main/java/bisq/desktop/main/dao/burnbsq/assetfee/AssetFeeView.java
> +        log.error("updateList");
```suggestion
```

2020-08-22 01:58 UTC, chimp1984 commented
> Would prefer to have pure refactoring as separate commits for easier review.

Agree. Sorry.

2020-08-22 02:52 UTC, ManfredKarrer commented
utACK

2020-08-22 12:56 UTC, sqrrm approved these changes
ACK

2020-08-22 12:56 UTC, merged