Use https:// for XMR explorer API endpoints, except if localhost or Tor
bisq-network/bisq pull request #4492
Opened 2020-09-07 03:04 UTC by wiz

2020-09-07 03:06 UTC, chimp1984 approved these changes, later dismissed
utACK

2020-09-07 04:35 UTC, jmacxx requested changes
As discussed, suggested change to simplify: `https://` prefix included in URL and then only need to detect localhost so as to disable socks5 proxy.  Regex changed to allow optional port specifier.  Defaults needs changing to include the https.  @Emzy service to use https also?

        httpClient.setBaseUrl(model.getServiceAddress());
        if (model.getServiceAddress().matches(".*127.0.0.1.*|.*.local.*|.*localhost.*")) {
            log.info("Ignoring Socks5 proxy for local net address: {}", model.getServiceAddress());
            httpClient.setIgnoreSocks5Proxy(true);
        }

2020-09-07 08:46 UTC, wiz commented
@jmacxx after thinking about it a bit more, that still isn't nearly enough to cover all the possible cases we need to support. let me work on some new regex.

2020-09-07 12:30 UTC, Emzy commented
utACK
I'm not a JAVA developer. The regex as far as I can parse them by eye look OK, also the tests.

Is there not a simpler way to detect a private IP address space (LAN address)?

2020-09-07 14:08 UTC, jmacxx commented
Problem: each time the user edits a url then restarts bisq, modify the url again the prefix is prepended, ends up like `https://https://node77.monero.wiz.biz`.  I suppose any existing prefix has to be removed before validating the url.

2020-09-07 14:15 UTC, chimp1984 commented
maybe easiest to just add the https to the textfield at input.

2020-09-07 15:10 UTC, jmacxx commented on core/src/main/java/bisq/core/trade/txproof/xmr/XmrTxProofRequest.java
> +        } if (model.getServiceAddress().regionMatches(0, "https:", 0, 6)) {
should be `else if`

2020-09-07 15:13 UTC, jmacxx requested changes

2020-09-07 15:13 UTC, jmacxx commented on core/src/main/java/bisq/core/trade/txproof/xmr/XmrTxProofRequest.java
> +        } if (model.getServiceAddress().regionMatches(0, "https:", 0, 6)) {
should be `else if`

2020-09-07 15:37 UTC, wiz commented
@jmacxx good catch, I forgot to strip the protocol prefix out, just pushed a commit that should fix that issue. I should have tested more, but I was trying to rush this out.

@chimp1984 maybe, and there is also the decision to route the connection through Tor or not, which would require its own slider switch - using regex we can strictly enforce https or Tor onion except for localhost or LAN ip address. IMO the goal is to let user be able to add xmrchain.net or whatever public explorers they want to trust, but without letting them accidentally put http:// and expose them to MITM attacks.

I'm also going to tweak the strings a bit with @m52go, since "Service addresses" is a big vague and user might be confused what exactly to enter. To be honest this feature feels like it needs a lot more testing and polish before we ship it in a public release to users...

2020-09-07 17:33 UTC, jmacxx approved these changes, later dismissed
ACK :+1: Tested out OK in both regtest and production.

![image](https://user-images.githubusercontent.com/47253594/92409300-c0343980-f105-11ea-8405-2a9f246838fb.png)



![image](https://user-images.githubusercontent.com/47253594/92409072-0341dd00-f105-11ea-8faa-07ec5c362766.png)


![image](https://user-images.githubusercontent.com/47253594/92409422-2caf3880-f106-11ea-9ba2-6c4aad956763.png)

2020-09-07 23:22 UTC, chimp1984 commented
I will review tomorrow, was out the whole day....

2020-09-08 02:48 UTC, wiz commented
@jmacxx thanks for testing with your http:// node on LAN with custom port number, this is exactly what we needed. you might also add xmrchain.net to the list which should use https://

2020-09-08 02:56 UTC, wiz commented
@chimp1984 after this PR, what do you think about making the list of Monero Explorers into a multi-line combobox like the ones for altcoins and fiat below? we could have a list of hard-coded ones enabled by default, and allow the user to enter their own into the list, would look nicer than a comma delimitated text input field

<img width="433" alt="Screen Shot 2020-09-08 at 11 54 46" src="https://user-images.githubusercontent.com/232186/92428483-38fcc980-f1ca-11ea-9dda-70345ef6d000.png">

2020-09-08 13:14 UTC, sqrrm reviewed
Code looks fine to me. Can't say the same for the regexes, but they might well be correct, I can't tell. If I can get another ack for regexes I'm fine with this PR. @Emzy that seems to be your forte :)

2020-09-08 14:04 UTC, chimp1984 commented
@wiz Which one are candidates? We could add one or 2 by default for more security. Only potential issue is that more services we use the higher the chance that one has a network issue and then auto-conf fails. Beside that, are those offering onion addresses and if not are they supporting Tor connections (no captcha)? 

I think a UI list is a bit too much for that feature as it would also overload more the settings UI as it is already...

2020-09-08 14:15 UTC, wiz commented
I agree, and Devin is going to setup a 3rd node instance for us so we should be fine for now. But that is not related to this PR i suppose, and we can think about it again later.

2020-09-08 14:44 UTC, Emzy commented
utACK

> Code looks fine to me. Can't say the same for the regexes, but they might well be correct, I can't tell. If I can get another ack for regexes I'm fine with this PR. @Emzy that seems to be your forte :)

The regexes and the networks to be local addresses look right. But I'm not a JAVA dev.
I haven't run the tests, but they also look good.

2020-09-08 15:21 UTC, Emzy commented
ACK
The test passed.
<img width="695" alt="Screen Shot 2020-09-08 at 17 19 13" src="https://user-images.githubusercontent.com/1223908/92495800-a5da8880-f1f7-11ea-8d30-2f864a2b4c01.png">

2020-09-08 16:15 UTC, chimp1984 approved these changes
utACK

2020-09-08 16:16 UTC, sqrrm approved these changes

2020-09-08 16:17 UTC, merged