Set initial value for bsqAverageTrimThreshold to 5% in case of an
bisq-network/bisq pull request #4747
Opened 2020-11-04 16:35 UTC by chimp1984

Fixes https://github.com/bisq-network/bisq/pull/4706#issuecomment-721833394

2020-11-04 17:05 UTC, cbeams requested changes
NACK. This change blindly sets the threshold value to 5% regardless of its previous value. I tested this by bringing up my client, setting the value to 1%, shutting it down and restarting it and noticing that the value reverted to 5%. I tried it again, thinking that perhaps my value didn't persist. I set it to 2%, clicked around to different screens in the UI, came back to settings, confirmed that 2% was still set, shut the client down and restarted, and once again the value was set to 5%. When fixing this, it should also be considered that 0% is a valid value, i.e. if someone sets that value, it should persist and not be reset to 5%. The implementation should check that the preference value is null/absent in order to force it to 5%, not just equivalent to 0.

2020-11-04 17:17 UTC, chimp1984 commented
Ah damn... was too much rushed...

2020-11-04 17:20 UTC, chimp1984 commented
Hm... not that easy to fix as default is 0 if protobug field was not set, but we allow 0 as value, so if we just check for 0 it would overwrite it when you set 0. I need to check if the protobuf reveals some more info it the field was undefined so we can set it to -1 and check for that... But busy atm with some issues with seed nodes...

2020-11-04 17:51 UTC, chimp1984 commented
Seems for primitive types there is no way to check if field was set and it delivers 0 if not set. @cbeams Do you know any way to deal with that? Wrapping the double in a protoDouble would work but thats ugly... Or we accept that when setting to 0 it will not persist your custom setting. Not that important feature anyway...

2020-11-05 08:24 UTC, cbeams approved these changes

2020-11-05 08:25 UTC, merged

2020-11-05 08:26 UTC, cbeams commented
ACK. I've tested the latest change and can confirm all works as expected. It is indeed unfortunate to not allow 0% as a legitimate value, but I agree that further work on this very minor feature is probably not worth it. The comment in the code is enough for now. Perhaps if someone complains about it, more work would be merited.