Fix copy of BankName value + BranchId/BankId
bisq-network/bisq pull request #5231
Opened 2021-02-24 11:22 UTC by BtcContributor

Fixes #5200

This PR deals with cases like:
- BankName / BranchId (as the original issue)
- BankName / BankId

It would be trivial to add other instances if present.

2021-03-11 15:51 UTC, ripcurlx requested changes
NACK - Please see my comments on the naming. Also for the future please have a look at https://chris.beams.io/posts/git-commit/. I'm not a great commit message writer myself, but I think there is some potential to grow :wink:

2021-03-11 15:51 UTC, ripcurlx commented on desktop/src/main/java/bisq/desktop/util/FormBuilder.java
> +                                                                                               boolean withoutBeforeSlash) {
When used with code completion this naming `withoutBeforeSlash` is not very intuitive. Maybe rename it to `onlyCopyTextAfterDelimiter`

2021-03-11 15:51 UTC, ripcurlx commented on desktop/src/main/java/bisq/desktop/components/TextFieldWithCopyIcon.java
> +    private boolean copyWithoutBeforeSlash;
As this code is independent of `/` I think it would be better to name it to `copyTextAfterDelimiter`

2021-03-11 16:56 UTC, BtcContributor commented
Thanks for all the feedback @ripcurlx!

2021-03-12 08:53 UTC, ripcurlx approved these changes
utACK

2021-03-12 08:54 UTC, merged

2021-04-28 19:02 UTC, Cha-cloud reviewed
How do you connect your github and localbitcoins account together

2021-05-02 00:15 UTC, pazza83 commented
Hi @Cha-cloud not sure what you are trying to do but probably best to make a post on https://bisq.community/ or ask on [Keybase](https://keybase.io/team/bisq)