Match SEPA accounts IBANs to selected participating countries #241
bisq-network/bisq pull request #5419
Opened 2021-04-19 11:20 UTC by AllyKaz

Auto fills bank county code based on a valid IBAN code and validates the IBAN on the selected bank country code.

Fixes #241

Auto-fills the bank country code based on the IBAN entered, conversely makes the selected bank country code part of the validation of the IBAN.

Wasn't too sure on how this should be tested (i.e. testpad), so thought I would leave to see if this is considered the right approach first.

2021-04-20 03:00 UTC, pazza83 commented
Hi @AllyKaz and @ripcurlx 

Does this address https://github.com/bisq-network/growth/issues/241 and https://github.com/bisq-network/bisq/issues/5384 ?

2021-04-20 07:16 UTC, ripcurlx commented
@AllyKaz Could you please sign your commits. Thanks!

2021-04-20 07:18 UTC, ripcurlx requested changes
NACK - Thanks for picking up this issue! Please see my comments regarding empty lines.

2021-04-20 07:18 UTC, ripcurlx commented on desktop/src/main/java/bisq/desktop/components/paymentmethods/SepaForm.java
> +
Could you please remove this unnecessary blank lines.

2021-04-20 07:18 UTC, ripcurlx commented on desktop/src/main/java/bisq/desktop/components/paymentmethods/SepaForm.java
> +
Could you please remove this unnecessary blank lines.

2021-04-20 07:18 UTC, ripcurlx commented on desktop/src/main/java/bisq/desktop/components/paymentmethods/SepaForm.java
> +
Could you please remove this unnecessary blank lines.

2021-04-20 07:18 UTC, ripcurlx commented on desktop/src/main/java/bisq/desktop/components/paymentmethods/SepaForm.java
> +
Could you please remove this unnecessary blank lines.

2021-05-10 07:04 UTC, cd2357 commented
@AllyKaz any updates? Looks like a promising PR.

2021-08-01 21:45 UTC, pazza83 commented
Please can this be kept open as it is yet to be implemented.

2022-03-18 11:44 UTC, xyzmaker123 commented
@ripcurlx This one could be closed now

2022-03-21 09:47 UTC, closed without merging