Added new test case to OfferTest
bisq-network/bisq pull request #5531
Opened 2021-05-26 04:55 UTC by ashah1220

Added a test case to check if resetState() works.

2021-05-26 08:07 UTC, ripcurlx requested changes
NACK - please see my comment

2021-05-26 08:07 UTC, ripcurlx commented on gradle/wrapper/gradle-wrapper.properties
> -distributionSha256Sum=11657af6356b7587bfb37287b5992e94a9686d5c8a0a1b60b87b9928a2decde5
Why did you try to remove the hash in this commit?

2021-05-27 22:01 UTC, ashah1220 commented on gradle/wrapper/gradle-wrapper.properties
> -distributionSha256Sum=11657af6356b7587bfb37287b5992e94a9686d5c8a0a1b60b87b9928a2decde5
The build fails for me unless I remove line 3 in the gradle properties.

2021-05-28 07:36 UTC, ripcurlx commented on gradle/wrapper/gradle-wrapper.properties
> -distributionSha256Sum=11657af6356b7587bfb37287b5992e94a9686d5c8a0a1b60b87b9928a2decde5
Could you please post the log output in that case?

2021-07-08 02:33 UTC, closed without merging