Avoid that outdated donation and fee addresses are used.
bisq-network/bisq pull request #5764
Opened 2021-10-18 20:18 UTC by chimp1984

Fixes https://github.com/bisq-network/bisq/issues/5762

In case we get an outdated donation address (RECIPIENT_BTC_ADDRESS)
we trigger a dao resync. The user get a popup for doing a restart
in that case.
For the fee address selection we do not fall back to the
RECIPIENT_BTC_ADDRESS in case no address from filter is provided
but we use the hard coded address of the current fee receiver address.

2021-10-19 03:07 UTC, jmacxx commented
Could be good to define the hardcoded addresses in `Config.java` since they are used in more than one place, and to avoid having them sprinkled through the code, 
see: `Param.java, DaoFacade.java, DelayedPayoutAddressProvider.java, TxValidatorTest.java`

---

    // Option name constants
    public static final String TESTNET_DONATION_ADDRESS = "2N4mVTpUZAnhm9phnxB7VrHB4aBhnWrcUrV";
    public static final String REGTEST_DONATION_ADDRESS = "2MzBNTJDjjXgViKBGnatDU3yWkJ8pJkEg9w";
    public static final String INITIAL_DONATION_ADDRESS = "1BVxNn3T12veSK6DgqwU4Hdn7QHcDDRag7";
    public static final String BURNINGMAN_2019 = "3EtUWqsGThPtjwUczw27YCo6EWvQdaPUyp";
    public static final String BURNINGMAN_2 = "3A8Zc1XioE2HRzYfbb5P8iemCS72M6vRJV";
    public static final String BURNINGMAN_3 = "34VLFgtFKAtwTdZ5rengTT2g2zC99sWQLC";

2021-10-20 21:07 UTC, ghost requested changes

2021-10-20 21:07 UTC, ghost commented on core/src/main/java/bisq/core/util/FeeReceiverSelector.java
> +        return "38bZBj5peYS3Husdz7AH3gEUiUbYRD951t";
This fails when run in regtest, suggest something like this:

    public static String getMostRecentAddress() {
        return Config.baseCurrencyNetwork().isMainnet() ? Config.LATEST_DONATION_ADDRESS :  // mainnet
                Config.baseCurrencyNetwork().isDaoBetaNet() ? Config.LATEST_DONATION_ADDRESS : // daoBetaNet
                        Config.baseCurrencyNetwork().isTestnet() ? Config.TESTNET_DONATION_ADDRESS : // testnet
                                Config.REGTEST_DONATION_ADDRESS; // regtest
    }

2021-11-02 13:42 UTC, ripcurlx approved these changes, later dismissed
utACK

2021-11-02 13:42 UTC, ripcurlx commented on core/src/main/java/bisq/core/util/FeeReceiverSelector.java
> +        return "38bZBj5peYS3Husdz7AH3gEUiUbYRD951t";
@chimp1984 Could you respond to @jmacxx comment, before merging? Thanks!

2021-11-02 16:04 UTC, chimp1984 commented
> Could be good to define the hardcoded addresses in `Config.java` since they are used in more than one place, and to avoid having them sprinkled through the code, see: `Param.java, DaoFacade.java, DelayedPayoutAddressProvider.java, TxValidatorTest.java`
> 
> ```
> public static final String TESTNET_DONATION_ADDRESS = "2N4mVTpUZAnhm9phnxB7VrHB4aBhnWrcUrV";
> public static final String REGTEST_DONATION_ADDRESS = "2MzBNTJDjjXgViKBGnatDU3yWkJ8pJkEg9w";
> public static final String INITIAL_DONATION_ADDRESS = "1BVxNn3T12veSK6DgqwU4Hdn7QHcDDRag7";
> public static final String LATEST_DONATION_ADDRESS = "38bZBj5peYS3Husdz7AH3gEUiUbYRD951t";
> public static final String BURNINGMAN_2019 = "3EtUWqsGThPtjwUczw27YCo6EWvQdaPUyp";
> public static final String BURNINGMAN_2 = "3A8Zc1XioE2HRzYfbb5P8iemCS72M6vRJV";
> public static final String BURNINGMAN_3 = "34VLFgtFKAtwTdZ5rengTT2g2zC99sWQLC";
> ```

Yes agree. I will update that PR once the other PRs are merged...

2021-11-02 16:05 UTC, chimp1984 commented on core/src/main/java/bisq/core/util/FeeReceiverSelector.java
> +        return "38bZBj5peYS3Husdz7AH3gEUiUbYRD951t";
Ok. Will have a look once the other PRs are merged and that gets ready again...

2021-11-09 20:01 UTC, ripcurlx approved these changes
utACK

2021-11-09 20:01 UTC, merged