Apply Localized Number Formatting To Transaction Details
bisq-network/bisq pull request #5902
Opened 2021-12-07 22:02 UTC by alvasw

Fixes #3145

By default all amounts are separated by a "." In some locales that is
not the correct separator. This change formats all amounts and
percentages using the correct locale.

2021-12-09 09:27 UTC, ripcurlx commented
Changing to a localized formatting broke some tests if a different locale than the US_en is set.
Having DE_de causes following tests to fail:
```
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended

bisq.desktop.main.offer.bisq_v1.createoffer.CreateOfferViewModelTest > testSyncMinAmountWithAmountWhenHigherMinAmountValueIsSet FAILED
    org.junit.ComparisonFailure at CreateOfferViewModelTest.java:222

bisq.desktop.main.offer.bisq_v1.createoffer.CreateOfferViewModelTest > testSyncMinAmountWithAmountWhenSameValueIsSet FAILED
    org.junit.ComparisonFailure at CreateOfferViewModelTest.java:206

bisq.desktop.main.offer.bisq_v1.createoffer.CreateOfferViewModelTest > testSyncMinAmountWithAmountUntilChanged FAILED
    org.junit.ComparisonFailure at CreateOfferViewModelTest.java:166

bisq.desktop.main.offer.bisq_v1.createoffer.CreateOfferViewModelTest > testSyncPriceMarginWithVolumeAndFixedPrice FAILED
    org.junit.ComparisonFailure at CreateOfferViewModelTest.java:237

bisq.desktop.main.offer.bisq_v1.createoffer.CreateOfferViewModelTest > testSyncMinAmountWithAmountWhenZeroCoinIsSet FAILED
    org.junit.ComparisonFailure at CreateOfferViewModelTest.java:189

bisq.desktop.main.offer.offerbook.OfferBookViewModelTest > testGetPrice FAILED
    org.junit.ComparisonFailure at OfferBookViewModelTest.java:453

bisq.desktop.util.DisplayUtilsTest > testFormatSameVolume FAILED
    org.junit.ComparisonFailure at DisplayUtilsTest.java:67

bisq.desktop.util.DisplayUtilsTest > testFormatDifferentVolume FAILED
    org.junit.ComparisonFailure at DisplayUtilsTest.java:79

126 tests completed, 8 failed, 7 skipped

> Task :desktop:test FAILED
```

Could you please adapt those tests, so they don't use the current locale - Thanks!

2021-12-10 21:36 UTC, alvasw commented
Oops, didn't think about that. I switched my OS to German and fixed the code.

2021-12-20 10:30 UTC, ripcurlx requested changes
NACK - There are a couple of issues that need to get addressed.

If we localize the BSQ formatting it also needs to be done in one go for the other number formatting as well. Otherwise we end in situations like in this screenshot:
<img width="1259" alt="Bildschirmfoto 2021-12-20 um 11 27 11" src="https://user-images.githubusercontent.com/170962/146752850-8dd82d38-b3dd-4680-91c5-1aa6d4b20bed.png">

I also found an exception when clicking around on the Mainnet app when entering `Facts & Figures > BSQ Supply`.
```
java.lang.NumberFormatException: For input string: "0,00"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.base/java.lang.Double.parseDouble(Double.java:549)
	at bisq.desktop.main.dao.economy.supply.dao.DaoChartViewModel$1.toString(DaoChartViewModel.java:91)
	at bisq.desktop.main.dao.economy.supply.dao.DaoChartViewModel$1.toString(DaoChartViewModel.java:88)
	at javafx.scene.chart.NumberAxis.measureTickMarkSize(NumberAxis.java:334)
```

 I haven't tried it out yet, but I think it is also good to try out a regular BSQ trade (Altcoin or Altcoin instant) to see if the amount copy & pasting also doesn't have any issues with the new formatting.

2022-01-26 10:54 UTC, ripcurlx commented
@alvasw Do you want to continue to work on this or is this open for other developers to pick it up from here?

2022-01-26 15:55 UTC, alvasw commented
Hey @ripcurlx!
Sorry for stalling this pull request. I'm pretty busy at the moment. It's open for anyone to continue.

2022-01-26 15:55 UTC, closed without merging

2022-01-26 16:12 UTC, ghubstan commented
> Fixes #3145
> 
> By default all amounts are separated by a "." In some locales that is not the correct separator. This change formats all amounts and percentages using the correct locale.

I am a little late to respond to this, but using the US locale for CLI output was a deliberate decision at the beginning of the Bisq 1 API work.  So was using English for all CLI console output.