Standardize blockchain explorer URL usage
bisq-network/bisq pull request #6319
Opened 2022-08-10 16:51 UTC by Android-X13

This is an attempt to handle blockchain URLs consistently across the application.

While trying to delve into the GUI code I noticed there isn't a uniform way for opening txIDs/addresses in a blockchain explorer and some code that can be reused is instead getting re-implemented in various places.

2022-08-10 18:30 UTC, ripcurlx commented
@jmacxx Could you please review this and other PRs right now, as I'm on vacation and with only limited internet time in the evening 😅

2022-08-11 16:13 UTC, jmacxx commented
Will do, @ripcurlx.

2022-08-11 22:11 UTC, jmacxx requested changes
The description of this PR should explain that it is a code cleanup and no functionality changes are expected.

One questionable item is passing a `boolean` to signify isBsq in `openTxInBlockExplorer` and `openAddressInBlockExplorer`.  Nit picking, but my preference is that appropriate method names explain functionality clearer than passing a true/false.

Overall, a very good cleanup PR.

2022-08-11 22:11 UTC, ghost commented on desktop/src/main/java/bisq/desktop/util/GUIUtil.java
> +            openWebPage(getTxUrl(txId, isBsq), false);
Legacy nit: current Bisq coding standards dictate use of curly braces for all conditional statements even one liners.

2022-08-11 22:11 UTC, ghost commented on desktop/src/main/java/bisq/desktop/util/GUIUtil.java
> +            openWebPage(getAddressUrl(address, isBsq), false);
Nit: current Bisq coding standards dictate use of curly braces for all conditional statements even one liners.

2022-08-11 22:11 UTC, ghost commented on desktop/src/main/java/bisq/desktop/main/overlays/windows/ManualPayoutTxWindow.java
> +                GUIUtil.openTxInBlockExplorer(depositTxHex.getText());
Nit: current Bisq coding standards dictate use of curly braces for all conditional statements even one liners.

2022-08-12 11:55 UTC, Android-X13 commented
Hi @jmacxx, I can modify the GUIUtil methods to not expect an additional boolean parameter if you prefer. I'll have to reintroduce a check in `TxIdTextField` and `ExplorerAddressTextField` about whether to open bsq or non-bsq addresses/txIDs (I think that is why I made the methods the way they are in the PR).
Shall I make the changes?

2022-08-12 12:37 UTC, jmacxx commented
Yes, sounds good.

2022-08-12 17:46 UTC, jmacxx approved these changes
ACK

2022-08-17 11:26 UTC, ripcurlx approved these changes
utACK - based on https://github.com/bisq-network/bisq/pull/6319#pullrequestreview-1071435607

2022-08-17 11:26 UTC, merged