API: gettransactions method
bisq-network/bisq pull request #6680
Opened 2023-05-06 15:55 UTC by helixx87

```
./bisq-cli --password=xyz gettransactions
```

2023-05-09 08:45 UTC, alvasw requested changes
Nit

2023-05-09 08:45 UTC, alvasw commented on cli/src/main/java/bisq/cli/table/builder/TransactionTableBuilder.java
> +        List<TxInfo> transactions = protos.stream().map(p -> (TxInfo) p).collect(Collectors.toList());
You can avoid creating the `List` here by replacing this line with:
```
Stream<TxInfo> transactions = protos.stream()
                .map(p -> (TxInfo) p);
```

2023-05-09 08:45 UTC, alvasw commented on core/src/main/java/bisq/core/api/CoreWalletsService.java
> +        return btcWalletService.getTransactions(false).stream().collect(Collectors.toList());
`btcWalletService.getTransactions(false)` returns a `Set`. You can pass that `Set` to `GetTransactionsReply.newBuilder().addAllTxInfo(...)` because it accepts any `Iterable<? extends TxInfo>`.

2023-05-20 08:32 UTC, helixx87 commented on cli/src/main/java/bisq/cli/table/builder/TransactionTableBuilder.java
> +        List<TxInfo> transactions = protos.stream().map(p -> (TxInfo) p).collect(Collectors.toList());
Great catch - fixed it.

2023-05-20 08:32 UTC, helixx87 commented on core/src/main/java/bisq/core/api/CoreWalletsService.java
> +        return btcWalletService.getTransactions(false).stream().collect(Collectors.toList());
Fixed

2023-05-20 09:37 UTC, helixx87 commented
Thanks @alvasw for review and valuable suggestions regarding code quality. I introduced them here using `git commit --amend`.

2023-05-26 06:37 UTC, alvasw requested changes
Code changes look good to me! :+1: 

When I run `bisq-cli --help`, I cannot find the `gettransactions` method in the list.
```
gettxfeerate                                                                 Get current tx fee rate in sats/byte

settxfeerate             --tx-fee-rate=<sats/byte>                           Set custom tx fee rate in sats/byte

unsettxfeerate                                                               Unset custom tx fee rate

gettransaction           --transaction-id=<transaction-id>                   Get transaction with id

createoffer              --payment-account=<payment-account-id> \            Create and place an offer
                         --direction=<buy|sell> \                            
                         --currency-code=<currency-code> \                   
                         --amount=<btc-amount> \                             
```

2023-06-20 12:50 UTC, alvasw approved these changes
ACK

2023-06-20 13:13 UTC, alejandrogarcia83 approved these changes
utACK

2023-06-20 13:14 UTC, merged