Fix bisq.properties pickup in ApiTest
bisq-network/bisq pull request #6724
Opened 2023-06-06 19:54 UTC by AllyKaz

This change copies the 'bisq.properties' file in apitest/src/main/resources to each instance's DataDir on test harness startup.

This was necessary as #5718 was not copying the file into the instance's data dir but leaving it in 'build/resources/main' where it wasn't picked up by the instance.

Fixes #replaceWithIssueNr, fixes #replaceWithIssueNr

Your PR description here.

2023-06-14 12:15 UTC, alvasw requested changes
Do we need to delete the `bisq.properties` file in the root directory? The deletion breaks the Gradle Build Cache. It's smarter to include/exclude the file explicitly [1], or even have them multiple times (for all instances) in the resources directory.

I know that you didn't write the initial file-deletion code.

[1] https://docs.gradle.org/current/dsl/org.gradle.language.jvm.tasks.ProcessResources.html

2023-06-14 12:15 UTC, alvasw commented on apitest/src/main/java/bisq/apitest/Scaffold.java
> +            deleteRedundantBisqPropertiesFile();
I know, you didn't write this code, but do we need to delete the `bisq.properties` file? This breaks the Gradle Build Cache.

2023-06-21 21:26 UTC, AllyKaz commented on apitest/src/main/java/bisq/apitest/Scaffold.java
> +            deleteRedundantBisqPropertiesFile();
I think it seems fine to leave. It's presence can act as a sign the files were copied from a single 'master' file and it's absence as a sign of explicit inclusion. 

I've made the build file copy the bisq.properties file into the relevant directories if it's present and have removed the equivalent logic from Scaffold along with that which deletes the file.

I've also refactored the dao-setup.gradle file to remove some redundant copy and renaming.

2023-06-23 00:11 UTC, AllyKaz commented on apitest/src/main/java/bisq/apitest/Scaffold.java
> +            deleteRedundantBisqPropertiesFile();
I think it's fine to keep, its presence signals it's being used by all instances, and its absence signals explicit inclusion.

I've removed `deleteRedundantBisqPropertiesFile()` and done some refactoring on `dao-setup.gradle`, removing some redundant copying and renaming.

2023-07-01 18:26 UTC, alvasw requested changes
Looks good!

2023-07-01 18:26 UTC, alvasw commented on apitest/src/main/java/bisq/apitest/Scaffold.java
> +import java.util.Arrays;
This is import is not needed anymore.

2023-07-01 18:26 UTC, alvasw commented on apitest/src/main/java/bisq/apitest/Scaffold.java
> +    }
Please reformat this to:
```diff
     }
+
     private void copyBisqPropertiesFileToAppDataDir(BisqAppConfig bisqAppConfig) throws IOException, InterruptedException {
-        if(!new File(config.baseSrcResourcesDir + "/bisq.properties").exists()) return;
+        if (!new File(config.baseSrcResourcesDir + "/bisq.properties").exists()) return;
 
         String instanceDataDir = config.rootAppDataDir + "/" + bisqAppConfig.appName;
```

2023-07-04 18:01 UTC, AllyKaz commented on apitest/src/main/java/bisq/apitest/Scaffold.java
> +    }
Amended as instructed.

2023-07-06 15:31 UTC, alvasw approved these changes
utACK

2023-07-06 19:27 UTC, alejandrogarcia83 approved these changes
utACK

2023-07-06 19:27 UTC, merged