Suspend instances in Apitest by CSV list in apitest.properties
bisq-network/bisq pull request #6727
Opened 2023-06-10 10:47 UTC by AllyKaz

There's currently no way to suspend any subset of instances in debugging mode in Apitest.

This change enables any or all instances to be suspended in debugging mode by the inclusion of the instance name(s) in a CSV list in the apitest.properties file.

2023-07-01 18:10 UTC, alvasw requested changes
Looks good!

2023-07-01 18:10 UTC, alvasw commented on apitest/src/main/java/bisq/apitest/linux/BisqProcess.java
> +        this.debugOpts = config.enableBisqDebugging? " -agentlib:jdwp=transport=dt_socket,server=y,"
Please reformat this to:
```diff
                 + "/scripts/get-bisq-pid.sh";
-        this.debugOpts = config.enableBisqDebugging? " -agentlib:jdwp=transport=dt_socket,server=y,"
-                + "suspend=" + (Arrays.asList(config.suspendedInstances.split(",")).contains(bisqAppConfig.name())?"y":"n")
+        this.debugOpts = config.enableBisqDebugging ? " -agentlib:jdwp=transport=dt_socket,server=y,"
+                + "suspend=" + (Arrays.asList(config.suspendedInstances.split(",")).contains(bisqAppConfig.name()) ? "y" : "n")
                 + ",address=*:" + bisqAppConfig.remoteDebugPort
```

2023-07-04 20:45 UTC, AllyKaz commented on apitest/src/main/java/bisq/apitest/linux/BisqProcess.java
> +        this.debugOpts = config.enableBisqDebugging? " -agentlib:jdwp=transport=dt_socket,server=y,"
Fixed formatting as requested.

2023-07-06 15:37 UTC, alvasw approved these changes
utACK

2023-07-06 19:29 UTC, alejandrogarcia83 approved these changes
utACK

2023-07-06 19:29 UTC, merged