Update data stores for v1.9.15
bisq-network/bisq pull request #7035
Opened 2024-02-13 10:13 UTC by alejandrogarcia83

Light node in light mode and full node in dark mode
![light_1](https://github.com/bisq-network/bisq/assets/117378669/18f4c248-d635-4665-be82-497ca1292431)
![full_1](https://github.com/bisq-network/bisq/assets/117378669/7f881589-7a5d-402a-ba77-e1585dc1509b)
![light_2](https://github.com/bisq-network/bisq/assets/117378669/2db636be-b13b-4a96-981b-6c3fc0439dad)
![full_2](https://github.com/bisq-network/bisq/assets/117378669/cbc2efa9-10e3-40a6-983a-b248603e0dc9)
![light_3](https://github.com/bisq-network/bisq/assets/117378669/8b6b7e3f-8c18-43e0-8464-d15f31733e67)
![full_3](https://github.com/bisq-network/bisq/assets/117378669/f3c7b260-4a4b-4623-8dea-bda05df01b33)
![light_4](https://github.com/bisq-network/bisq/assets/117378669/a5fd9161-5ef7-48d9-a8e5-0be0754efc9c)
![full_4](https://github.com/bisq-network/bisq/assets/117378669/5530f52c-ab39-4326-a2f7-7f22a35a4a46)

2024-02-13 10:14 UTC, alejandrogarcia83 commented
@alvasw @HenrikJannsen @jmacxx Could anyone of you ACK this PR? Thanks!

2024-02-13 15:08 UTC, ghost requested changes
Please also consider setting `PROPOSAL_412_ACTIVATION_DATE` which should be set to a few weeks after release date.  See https://github.com/bisq-network/proposals/issues/412#issuecomment-1492851657


> As both traders need to have the exact same distribution for the delayed payout transaction we would need to roll that change out with a activation blockheight sufficiently far in the future so that we can be sure to release and enforce the updated version.

2024-02-13 15:08 UTC, jmacxx commented on common/src/main/java/bisq/common/app/Version.java
> +            "1.9.5", "1.9.6", "1.9.7", "1.9.10", "1.9.11", "1.9.13", "1.9.15");
`VERSION = "1.9.15"`
`HISTORICAL...TAGS` would have 1.9.14 (the prior version) appended.

2024-02-15 10:40 UTC, HenrikJannsen commented
I can confirm that my hashes on a light node are the same.

2024-02-25 07:22 UTC, alvasw commented on common/src/main/java/bisq/common/app/Version.java
> +            "1.9.5", "1.9.6", "1.9.7", "1.9.10", "1.9.11", "1.9.13", "1.9.15");
This is correct! 1.9.14 was a hotfix release without data store updates.

2024-02-25 07:22 UTC, alvasw approved these changes
utACK

DAO hashes match with my nodes too.

2024-02-25 14:32 UTC, merged