Add suddenwhipvapor mediator instance onion
bisq-network/bisq pull request #7334
Opened 2024-12-22 23:42 UTC by suddenwhipvapor

As https://github.com/bisq-network/proposals/issues/464 was approved by DAO vote, this PR adds the onion address of my mediator instance.

2024-12-27 06:10 UTC, alejandrogarcia83 requested changes

2024-12-27 06:10 UTC, alejandrogarcia83 commented on docs/build.md
I think you accidentally committed this file to your PR. You are reverting your previous PR (https://github.com/bisq-network/bisq/pull/7327).

2024-12-27 19:37 UTC, suddenwhipvapor commented on docs/build.md
I am github-dumb. The point of reverting the build.md file both in this PR and the next one was to create a PR that only contained the new edits... now that you merged the build.md PR I think I will delete my fork, create a new one, and commit changes to branches of that fork rather than to the master.
Let me see.

2024-12-27 19:41 UTC, suddenwhipvapor commented on docs/build.md
Ok it should be fixed, I will do the same with the remaining PR.

2025-01-04 15:27 UTC, HenrikJannsen commented
@suddenwhipvapor Can you squash the 3 commits so the accidental commits disappear?

2025-01-04 15:52 UTC, closed without merging